---
permalink: sm-storage/automatic-versus-manual-host-creation.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, automatic, manual, host,
summary: "Creating a host is one of the steps required to let the storage array know which hosts are attached to it and to allow I/O access to the volumes. You can create a host automatically or manually."
---
= Automatic versus manual host creation
:icons: font
:imagesdir: ../media/

[.lead]
Creating a host is one of the steps required to let the storage array know which hosts are attached to it and to allow I/O access to the volumes. You can create a host automatically or manually.

== Automatic creation

Automatic host creation for SCSI-based (not NVMe-oF) hosts is initiated by the Host Context Agent (HCA). The HCA is a utility that you can install on each host attached to the storage array. Each host that has the HCA installed pushes its configuration information to the storage array controllers through the I/O path. Based on the host information, the controllers automatically create the host and the associated host ports and set the host type. If needed, you can make any additional changes to the host configuration using System Manager.

After the HCA performs its automatic detection, the host automatically appears in the Hosts page with the following attributes:

* The host name derived from the system name of the host.
* The host identifier ports that are associated with the host.
* The Host Operating System Type of the host.

Hosts are created as stand-alone hosts; the HCA does not automatically create or add to host clusters.

== Manual creation

You might want to manually create a host for one of the following reasons:

. You chose not to install the HCA utility on your hosts.
. You want to ensure that the host port identifiers that were detected by the storage array controllers are associated correctly with the hosts.

During manual host creation, you associate host port identifiers by selecting them from a list or manually entering them. After you create a host, you can assign volumes to it or add it to a host cluster if you plan to share access to volumes.
