---
permalink: sm-storage/concept_why_can_t_i_choose_another_amount_to_decrease_by.html
sidebar: sidebar
keywords: 
summary: 'You can decrease reserved capacity only by the amount you used to increase it. Reserved capacity for member volumes can be removed only in the reverse order they were added.'
---
= Why can't I choose another amount to decrease by?
:icons: font
:imagesdir: ../media/

[.lead]
You can decrease reserved capacity only by the amount you used to increase it. Reserved capacity for member volumes can be removed only in the reverse order they were added.

You cannot decrease the reserved capacity for a storage object if one of these conditions exists:

* If the storage object is a mirrored pair volume.
* If the storage object contains only one volume for reserved capacity. The storage object must contain at least two volumes for reserved capacity.
* If the storage object is a disabled snapshot volume.
* If the storage object contains one or more associated snapshot images.

You can remove volumes for reserved capacity only in the reverse order that they were added.

You cannot decrease the reserved capacity for a snapshot volume that is read-only because it does not have any associated reserved capacity. Only snapshot volumes that are read-write require reserved capacity.
