---
permalink: sm-storage/concept_why_would_i_want_to_manually_configure_a_pool.html
sidebar: sidebar
keywords: 
summary: 'The following examples describe why you would want to manually configure a pool.'
---
= Why would I want to manually configure a pool?
:icons: font
:imagesdir: ../media/

[.lead]
The following examples describe why you would want to manually configure a pool.

* If you have multiple applications on your storage array and do not want them competing for the same drive resources, you might consider manually creating a smaller pool for one or more of the applications.
+
You can assign just one or two volumes instead of assigning the workload to a large pool that has many volumes across which to distribute the data. Manually creating a separate pool that is dedicated to the workload of a specific application can allow storage array operations to perform more rapidly, with less contention.
+
To manually create a pool: Select *Storage*, and then select *Pools & Volume Groups*. From the *All Capacity* tab, click *Create* > *Pool*.

* If there are multiple pools of the same drive type, a message appears indicating that System Manager cannot recommend the drives for a pool automatically. However, you can manually add the drives to an existing pool.
+
To manually add drives to an existing pool: From the *Pools & Volume Groups* page, select the pool, and then click *Add Capacity*.
