---
permalink: sm-storage/concept_why_am_i_seeing_a_capacity_over_allocation_error_when_i_have_enough_free_capacity_in_a_volume_group_to_create_volumes.html
sidebar: sidebar
keywords: 
summary: 'The selected volume group might have one or more free capacity areas. A free capacity area is the free capacity that can result from deleting a volume or from not using all available free capacity during volume creation.'
---
= Why am I seeing a capacity over-allocation error when I have enough free capacity in a volume group to create volumes?
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
The selected volume group might have one or more free capacity areas. A free capacity area is the free capacity that can result from deleting a volume or from not using all available free capacity during volume creation.

When you create a volume in a volume group that has one or more free capacity areas, the volume's capacity is limited to the largest free capacity area in that volume group. For example, if a volume group has a total of 15 GiB free capacity, and the largest free capacity area is 10 GiB, the largest volume you can create is 10 GiB.

If a volume group has free capacity areas, the volume group graph contains a link indicating the number of existing free capacity areas. Select the link to display a pop-over that indicates the capacity of each area.

By consolidating free capacity, you can create additional volumes from the maximum amount of free capacity in a volume group. You can consolidate the existing free capacity on a selected volume group using one of the following methods:

* When at least one free capacity area is detected for a volume group, the *Consolidate free capacity* recommendation appears on the *Home* page in the Notification area. Click the *Consolidate free capacity* link to launch the dialog box.
* You can also select menu:Pools & Volume Groups[Uncommon Tasks > Consolidate volume group free capacity] to launch the dialog box.

If you want to use a specific free capacity area rather than the largest free capacity area, use the Command Line Interface (CLI).
