---
permalink: sm-storage/concept_what_is_a_pool.html
sidebar: sidebar
keywords: 
summary: 'A pool is a set of drives that is logically grouped. You can use a pool to create one or more volumes accessible to a host. \(You create volumes from either a pool or a volume group.\)'
---
= What is a pool?
:icons: font
:imagesdir: ../media/

[.lead]
A pool is a set of drives that is logically grouped. You can use a pool to create one or more volumes accessible to a host. (You create volumes from either a pool or a volume group.)

Pools can eliminate the need for administrators to monitor usage on each host to determine when they are likely to run out of storage space and avoid conventional disk resizing outages. When a pool nears depletion, additional drives can be added to the pool non-disruptively and capacity growth is transparent to the host.

With pools, data is automatically re-distributed to maintain equilibrium. By distributing parity information and spare capacity throughout the pool, every drive in the pool can be used to rebuild a failed drive. This approach does not use dedicated hot spare drives; instead, preservation (spare) capacity is reserved throughout the pool. Upon drive failure, segments on other drives are read to recreate the data. A new drive is then chosen to write each segment that was on a failed drive so that data distribution across drives is maintained.
