---
permalink: sm-storage/concept_why_does_the_data_display_as_zero_in_the_graphs_and_table.html
sidebar: sidebar
keywords: 
summary: 'When a zero is displayed for a data point in the graphs and table, it means there is no I/O activity for the object for that point in time. This situation could occur because the host is not initiating I/O to that object, or it could be a problem with the object itself.'
---
= Why does data display as zero in the graphs and table?
:icons: font
:imagesdir: ../media/

[.lead]
When a zero is displayed for a data point in the graphs and table, it means there is no I/O activity for the object for that point in time. This situation could occur because the host is not initiating I/O to that object, or it could be a problem with the object itself.

The historical data for the object is still available for viewing. The graphs and table will show non-zero data once I/O activity begins occurring for the object.

The following table lists the most common reasons why a data point value might be zero for any given object.

|===
| Array-level object type| Reason data displays as zero
a|
Volume
a|

* Volume had no host assignment.

a|
Volume group
a|

* Volume group is being imported.
* Volume group does not contain a volume that is assigned to a host, *_and_* volume group does not contain any reserved capacity.

a|
Drive
a|

* Drive has failed.
* Drive has been removed.
* Drive is in an unknown state.

a|
Controller
a|

* Controller is offline.
* Controller has failed.
* Controller has been removed.
* Controller is in an unknown state.

a|
Storage array
a|

* Storage array does not contain volumes.

|===
