---
permalink: sm-storage/concept_what_is_a_snapshot_group.html
sidebar: sidebar
keywords: 
summary: 'A snapshot group is a collection of point-in-time snapshot images of a single associated base volume.'
---
= What is a snapshot group?
:icons: font
:imagesdir: ../media/

[.lead]
A snapshot group is a collection of point-in-time snapshot images of a single associated base volume.

System Manager organizes snapshot images into _snapshot groups_. Snapshot groups require no user action, but you can adjust reserved capacity on a snapshot group at any time. Additionally, you might be prompted to create reserved capacity when the following conditions are met:

* Any time you take a snapshot of a base volume that does not yet have a snapshot group, System Manager automatically creates a snapshot group. This creates reserved capacity for the base volume that is used to store subsequent snapshot images.
* Any time you create a snapshot schedule for a base volume, System Manager automatically creates a snapshot group.
