---
permalink: sm-storage/concept_how_do_i_maintain_shelf_drawer_loss_protection.html
sidebar: sidebar
keywords: 
summary: 'To maintain shelf/drawer loss protection for a pool or volume group, use the criteria specified in the following table.'
---
= How do I maintain shelf/drawer loss protection?
:icons: font
:imagesdir: ../media/

[.lead]
To maintain shelf/drawer loss protection for a pool or volume group, use the criteria specified in the following table.

|===
| Level| Criteria for shelf/drawer loss protection| Minimum number of shelves/drawers required
a|
Pool

a|
For shelves, the pool must contain no more than two drives in a single shelf.

For drawers, the pool must include an equal number of drives from each drawer.

a|
6 for shelves

5 for drawers

a|
RAID 6

a|
The volume group contains no more than two drives in a single shelf or drawer.

a|
3

a|
RAID 3 or RAID 5

a|
Each drive in the volume group is located in a separate shelf or drawer.

a|
3

a|
RAID 1

a|
Each drive in a mirrored pair must be located in a separate shelf or drawer.

a|
2

a|
RAID 0

a|
Cannot achieve shelf/drawer loss protection.

a|
Not applicable

|===

[NOTE]
====
Shelf/drawer loss protection is not maintained if a drive has already failed in the pool or volume group. In this situation, losing access to a drive shelf or drawer, and consequently another drive in the pool or volume group, causes loss of data.
====
