---
permalink: sm-storage/create-snapshot-consistency-group-step-2.html
sidebar: sidebar
keywords: reserve, capacity, snapshot, consistency, group
summary: "Associate reserved capacity to the snapshot consistency group. System Manager suggests the volumes and capacity based on the properties of the snapshot consistency group. You can accept the recommended reserved capacity configuration or customize the allocated storage."
---
= Step 2: Reserve capacity for snapshot consistency group
:icons: font
:imagesdir: ../media/

[.lead]
Associate reserved capacity to the snapshot consistency group. System Manager suggests the volumes and capacity based on the properties of the snapshot consistency group. You can accept the recommended reserved capacity configuration or customize the allocated storage.

== About this task

On the Reserve Capacity dialog box, the volume candidate table displays only the candidates that support the reserved capacity specified. Reserved capacity is the physical allocated capacity that is used for any copy service operation and storage object. It is not directly readable by the host.

.Steps

. Use the spinner box to allocate the reserved capacity for the snapshot consistency group. Do one of the following actions:
 ** *Accept the default settings*.
+
Use this recommended option to allocate the reserved capacity for each member volume with the default settings.

 ** *Allocate your own reserved capacity settings to meet your data storage needs.*
+
Allocate the reserved capacity using the following guidelines.

*** The default setting for reserved capacity is 40% of the capacity of the base volume. Usually this capacity is sufficient.
*** The capacity needed varies, depending on the frequency and size of I/O writes to the volumes and the quantity and duration of snapshot image collection.
. *Optional:* If you change the default reserved capacity setting, click *Refresh Candidates* to refresh the candidate list for the reserved capacity you specified.
. Click *Next*, and go to xref:create-snapshot-consistency-group-step-3.adoc[Step 3: Edit settings].
