---
permalink: sm-storage/create-snapshot-volume-step-4.html
sidebar: sidebar
keywords: edit, settings, snapshot, volume
summary: "Change the settings for a snapshot volume such as its name, caching, reserved capacity alert thresholds, and so on."
---
= Step 4: Edit settings for a snapshot volume
:icons: font
:imagesdir: ../media/

[.lead]
Change the settings for a snapshot volume such as its name, caching, reserved capacity alert thresholds, and so on.

.About this task

You can add the volume to solid-state disk (SSD) cache as a way to improve read-only performance. SSD cache consists of a set of SSD drives that you logically group together in your storage array.

.Steps

. Accept or change the settings for the snapshot volume as appropriate.
+
.Field Details
[%collapsible]
====

[cols="1a,1a" options="header"]
|===
| Setting| Description
2+a|
*Snapshot volume settings*
a|
Name
a|
Specify the name for the snapshot volume.
a|
Enable SSD Cache
a|
Choose this option to enable read-only caching on SSDs.
NOTE: This feature is not available on the EF600 or EF300 storage system.

2+a|
*Reserved capacity settings*
a|
Alert me when...
a|
*Appears only for a read/write snapshot volume*.

Use the spinner box to adjust the percentage point at which the system sends an alert notification when the reserved capacity for a snapshot group is nearing full.

When the reserved capacity for the snapshot group exceeds the specified threshold, use the advance notice to increase reserved capacity or to delete unnecessary objects before the remaining space runs out.
|===
====

. Review the snapshot volume configuration. Click *Back* to make any changes.
. When you are satisfied with your snapshot volume configuration, click *Finish*.
