---
permalink: sm-storage/create-snapshot-volume-step-1.html
sidebar: sidebar
keywords: review, members, snapshot, volume
summary: "Select either a snapshot image of a base volume or a snapshot consistency group. If you select a snapshot consistency group snapshot image, the member volumes of the snapshot consistency group appear for review."
---
= Step 1: Review members for a snapshot volume
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
Select either a snapshot image of a base volume or a snapshot consistency group. If you select a snapshot consistency group snapshot image, the member volumes of the snapshot consistency group appear for review.

.Steps

. Select menu:Storage[Snapshots].
. Select the *Snapshot Volumes* tab.
. Select *Create*.
+
The *Create Snapshot Volume* dialog box appears.

. Select the snapshot image (volume or snapshot consistency group) you want to convert into a snapshot volume, and then click *Next*. Use a text entry in the *Filter* field to narrow down the list.
+
If the selection was for a snapshot consistency group snapshot image, the *Review Members* dialog box appears.
+
On the *Review Members* dialog box, review the list of volumes that are selected for conversion to snapshot volumes, and then click *Next*.

. Go to xref:create-snapshot-volume-step-2.adoc[Step 2: Assign snapshot volume to host].
