---
permalink: sm-storage/create-volumes-hosts-step-3.html
sidebar: sidebar
keywords: add, edit, volumes
summary: "System Manager may suggest a volume configuration based on the application or workload you selected. This volume configuration is optimized based on the type of application the workload supports. You can accept the recommended volume configuration or you can edit it as needed. If you selected one of the 'Other' applications, you must manually specify the volumes and characteristics you want to create."
---
= Step 3: Add or edit volumes
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
System Manager may suggest a volume configuration based on the application or workload you selected. This volume configuration is optimized based on the type of application the workload supports. You can accept the recommended volume configuration or you can edit it as needed. If you selected one of the "Other" applications, you must manually specify the volumes and characteristics you want to create.

.Before you begin

* The pools or volume groups must have sufficient free capacity.
* The maximum number of volumes allowed in a volume group is 256.
* The maximum number of volumes allowed in a pool depends on the storage system model:
 ** 2,048 volumes (EF600 and E5700 series)
 ** 1,024 volumes (EF300)
 ** 512 volumes (E2800 series)
* To create a Data Assurance (DA)-enabled volume, the host connection you are planning to use must support DA.
+
Selecting a DA capable pool or volume group
+
If you want to create a DA-enabled volume, select a pool or volume group that is DA capable (look for *Yes* next to "DA" in the pool and volume group candidates table).
+
DA capabilities are presented at the pool and volume group level in System Manager. DA protection checks for and corrects errors that might occur as data is transferred through the controllers down to the drives. Selecting a DA-capable pool or volume group for the new volume ensures that any errors are detected and corrected.
+
If any of the host connections on the controllers in your storage array do not support DA, the associated hosts cannot access data on DA-enabled volumes.
* To create a secure-enabled volume, a security key must be created for the storage array.
+
Selecting a secure-capable pool or volume group
+
If you want to create a secure-enabled volume, select a pool or volume group that is secure capable (look for *Yes* next to "Secure-capable" in the pool and volume group candidates table).
+
Drive security capabilities are presented at the pool and volume group level in System Manager. Secure-capable drives prevent unauthorized access to the data on a drive that is physically removed from the storage array. A secure-enabled drive encrypts data during writes and decrypts data during reads using a unique _encryption key_.
+
A pool or volume group can contain both secure-capable and non-secure-capable drives, but all drives must be secure-capable to use their encryption capabilities.

* To create a resource-provisioned volume, all drives must be NVMe drives with the Deallocated or Unwritten Logical Block Error (DULBE) option.

.About this task

You create volumes from pools or volume groups. The *Add/Edit Volumes* dialog box shows all eligible pools and volume groups on the storage array. For each eligible pool and volume group, the number of drives available and the total free capacity appears.

For some application-specific workloads, each eligible pool or volume group shows the proposed capacity based on the suggested volume configuration and shows the remaining free capacity in GiB. For other workloads, the proposed capacity appears as you add volumes to a pool or volume group and specify the reported capacity.

.Steps

. Choose one of these actions based on whether you selected Other or an application-specific workload:
 ** *Other* -- Click *Add new volume* in each pool or volume group that you want to use to create one or more volumes.
+
.Field Details
[%collapsible]
====

[cols="1a,1a" options="header"]
|===
| Field| Description
a|
Volume Name
a|
A volume is assigned a default name by System Manager during the volume creation sequence. You can either accept the default name or provide a more descriptive one indicating the type of data stored in the volume.
a|
Reported Capacity
a|
Define the capacity of the new volume and the capacity units to use (MiB, GiB, or TiB). For *Thick volumes*, the minimum capacity is 1 MiB, and the maximum capacity is determined by the number and capacity of the drives in the pool or volume group.

Keep in mind that storage capacity is also required for copy services (snapshot images, snapshot volumes, volume copies, and remote mirrors); therefore, do not allocate all of the capacity to standard volumes.

Capacity in a pool is allocated in 4-GiB increments. Any capacity that is not a multiple of 4 GiB is allocated but not usable. To make sure that the entire capacity is usable, specify the capacity in 4-GiB increments. If unusable capacity exists, the only way to regain it is to increase the capacity of the volume.
a|
Volume Block Size (EF300 and EF600 only)
a|
Shows the block sizes that can be created for the volume:

  *** 512 -- 512 bytes
  *** 4K -- 4,096 bytes
a|
Segment Size
a|
Shows the setting for segment sizing, which only appears for volumes in a volume group. You can change the segment size to optimize performance.

*Allowed segment size transitions* -- System Manager determines the segment size transitions that are allowed. Segment sizes that are inappropriate transitions from the current segment size are unavailable on the drop-down list. Allowed transitions usually are double or half of the current segment size. For example, if the current volume segment size is 32 KiB, a new volume segment size of either 16 KiB or 64 KiB is allowed.

*SSD Cache-enabled volumes* -- You can specify a 4-KiB segment size for SSD Cache-enabled volumes. Make sure you select the 4-KiB segment size only for SSD Cache-enabled volumes that handle small-block I/O operations (for example, 16 KiB I/O block sizes or smaller). Performance might be impacted if you select 4 KiB as the segment size for SSD Cache-enabled volumes that handle large block sequential operations.

*Amount of time to change segment size* -- The amount of time to change a volume's segment size depends on these variables:

  *** The I/O load from the host
  *** The modification priority of the volume
  *** The number of drives in the volume group
  *** The number of drive channels
  *** The processing power of the storage array controllers

When you change the segment size for a volume, I/O performance is affected, but your data remains available.
a|
Secure-capable
a|
*Yes* appears next to "Secure-capable" only if the drives in the pool or volume group are secure-capable.

Drive Security prevents unauthorized access to the data on a drive that is physically removed from the storage array. This option is available only when the Drive Security feature has been enabled, and a security key is set up for the storage array.

A pool or volume group can contain both secure-capable and non-secure-capable drives, but all drives must be secure-capable to use their encryption capabilities.
a|
DA
a|
*Yes* appears next to "DA" only if the drives in the pool or volume group support Data Assurance (DA).

DA increases data integrity across the entire storage system. DA enables the storage array to check for errors that might occur as data is transferred through the controllers down to the drives. Using DA for the new volume ensures that any errors are detected.
a|
Resource provisioned (EF300 and EF600 only)
a|
*Yes* appears next to "Resource provisioned" only if the drives support this option. Resource Provisioning is a feature available in the EF300 and EF600 storage arrays, which allows volumes to be put in use immediately with no background initialization process.
|===
====

 ** *Application-specific workload* -- Either click *Next* to accept the system-recommended volumes and characteristics for the selected workload, or click *Edit Volumes* to change, add, or delete the system-recommended volumes and characteristics for the selected workload.
+
.Field Details
[%collapsible]
====

[cols="1a,1a" options="header"]
|===
| Field| Description
a|
Volume Name
a|
A volume is assigned a default name by System Manager during the volume creation sequence. You can either accept the default name or provide a more descriptive one indicating the type of data stored in the volume.
a|
Reported Capacity
a|
Define the capacity of the new volume and the capacity units to use (MiB, GiB, or TiB). For *Thick volumes*, the minimum capacity is 1 MiB, and the maximum capacity is determined by the number and capacity of the drives in the pool or volume group.

Keep in mind that storage capacity is also required for copy services (snapshot images, snapshot volumes, volume copies, and remote mirrors); therefore, do not allocate all of the capacity to standard volumes.

Capacity in a pool is allocated in 4-GiB increments. Any capacity that is not a multiple of 4 GiB is allocated but not usable. To make sure that the entire capacity is usable, specify the capacity in 4-GiB increments. If unusable capacity exists, the only way to regain it is to increase the capacity of the volume.
a|
Volume Type
a|
Volume type indicates the type of volume that was created for an application-specific workload.
a|
Volume Block Size (EF300 and EF600 only)
a|
Shows the block sizes that can be created for the volume:

  *** 512 -- 512 bytes
  *** 4K -- 4,096 bytes
a|
Segment Size
a|
Shows the setting for segment sizing, which only appears for volumes in a volume group. You can change the segment size to optimize performance.

*Allowed segment size transitions* -- System Manager determines the segment size transitions that are allowed. Segment sizes that are inappropriate transitions from the current segment size are unavailable on the drop-down list. Allowed transitions usually are double or half of the current segment size. For example, if the current volume segment size is 32 KiB, a new volume segment size of either 16 KiB or 64 KiB is allowed.

*SSD Cache-enabled volumes* -- You can specify a 4-KiB segment size for SSD Cache-enabled volumes. Make sure you select the 4-KiB segment size only for SSD Cache-enabled volumes that handle small-block I/O operations (for example, 16 KiB I/O block sizes or smaller). Performance might be impacted if you select 4 KiB as the segment size for SSD Cache-enabled volumes that handle large block sequential operations.

*Amount of time to change segment size* -- The amount of time to change a volume's segment size depends on these variables:

  *** The I/O load from the host
  *** The modification priority of the volume
  *** The number of drives in the volume group
  *** The number of drive channels
  *** The processing power of the storage array controllers

When you change the segment size for a volume, I/O performance is affected, but your data remains available.
a|
Secure-capable
a|
*Yes* appears next to "Secure-capable" only if the drives in the pool or volume group are secure-capable.

Drive security prevents unauthorized access to the data on a drive that is physically removed from the storage array. This option is available only when the drive security feature has been enabled, and a security key is set up for the storage array.

A pool or volume group can contain both secure-capable and non-secure-capable drives, but all drives must be secure-capable to use their encryption capabilities.
a|
DA
a|
*Yes* appears next to "DA" only if the drives in the pool or volume group support Data Assurance (DA).

DA increases data integrity across the entire storage system. DA enables the storage array to check for errors that might occur as data is transferred through the controllers down to the drives. Using DA for the new volume ensures that any errors are detected.
a|
Resource provisioned (EF300 and EF600 only)
a|
*Yes* appears next to "Resource Provisioned" only if the drives support this option. Resource Provisioning is a feature available in the EF300 and EF600 storage arrays, which allows volumes to be put in use immediately with no background initialization process.
|===
====

. To continue the volume creation sequence for the selected application, click *Next*, and go to xref:create-volumes-storage-step-4.adoc[Step 4: Review volume configuration].
