---
permalink: sm-storage/delete-snapshot-consistency-group.html
sidebar: sidebar
keywords: 
summary: 'You can delete snapshot consistency groups that are no longer needed.'
---
= Delete snapshot consistency group
:icons: font
:imagesdir: ../media/

[.lead]
You can delete snapshot consistency groups that are no longer needed.

== Before you begin

Confirm that the images for all member volumes are no longer needed for backup or testing purposes.

== About this task

This operation deletes all the snapshot images or schedules associated with the snapshot consistency group.

== Steps

. Select *Storage* > *Snapshots*.
. Select the *Snapshot Consistency Groups* tab.
. Select the snapshot consistency group that you want to delete, and then select *Uncommon Tasks* > *Delete*.
+
The Confirm Delete Snapshot Consistency Group dialog box appears.

. Confirm that you want to perform this operation, and then click *Delete*.

== Results

System Manager performs the following actions:

* Deletes all existing snapshot images and snapshot volumes from the snapshot consistency group.
* Deletes all the associated snapshot images that exist for each member volume in the snapshot consistency group.
* Deletes all the associated snapshot volumes that exist for each member volume in the snapshot consistency group.
* Deletes all associated reserved capacity for each member volume in the snapshot consistency group (if selected).
