---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html
sidebar: sidebar
keywords: 
summary: 'You can permanently disable resource provisioning on an existing pool or volume group.'
---
= Disable resource provisioning on existing volumes
:icons: font
:imagesdir: ../media/

[.lead]
You can permanently disable resource provisioning on an existing pool or volume group.

== Before you begin

* You must have an EF300 or EF600 storage array.
* You must have SSD volume groups or pools, where all the drives support the NVMe Deallocated or Unwritten Logical Block Error Enable (DULBE) error recovery capability. Otherwise, the "Disable resource provisioning" option is not available.

== About this task

Resource provisioning is a feature available in the EF300 and EF600 storage arrays, which allows volumes to be put in use immediately with no background initialization process. When you disable resource provisioning on a pool or volume group, a background operation rewrites all the logical blocks in every volume. Existing data remains intact.

[CAUTION]
====
Disabling resource provisioning is permanent. You cannot reverse this action (i.e., re-enable resource provisioning for these volume groups and pools).
====

== Steps

. Select *Storage* > *Pools & Volume Groups*.
. Select one pool or volume group from the list.
+
You can select only one pool or volume group at a time. Scroll down the list to see additional pools or volume groups.

. Select *Uncommon Tasks* > *Disable resource provisioning*.
. In the dialog box, confirm the operation.

== Results

A background operation rewrites all the logical blocks, keeping the existing data intact.
