---
permalink: sm-storage/functional-comparison-of-pools-and-volume-groups.html
sidebar: sidebar
keywords: functional, comparison, pools, volume, groups
summary: "The function and purpose of a pool and a volume group are the same. Both objects are a set of drives logically grouped together in a storage array and are used to create volumes that a host can access."
---
= Functional comparison of pools and volume groups
:icons: font
:imagesdir: ../media/

[.lead]
The function and purpose of a pool and a volume group are the same. Both objects are a set of drives logically grouped together in a storage array and are used to create volumes that a host can access.

The following table helps you decide whether a pool or volume group best suits your storage needs.

[cols="1a,1a,1a" options="header"]
|===
| Function| Pool| Volume Group
a|
Different RAID level supported
a|
No. Always RAID 6 in System Manager.
a|
Yes. RAID 0, 1, 10, 5, and 6 available.
a|
Thin volumes supported
a|
Yes
a|
No
a|
Full disk encryption (FDE) supported
a|
Yes
a|
Yes
a|
Data Assurance (DA) supported
a|
Yes
a|
Yes
a|
Shelf loss protection supported
a|
Yes
a|
Yes
a|
Drawer loss protection supported
a|
Yes
a|
Yes
a|
Mixed drive speeds supported
a|
Recommended to be the same, but not required. Slowest drive determines speed for all drives.
a|
Recommended to be the same, but not required. Slowest drive determines speed for all drives.
a|
Mixed drive capacity supported
a|
Recommended to be the same, but not required. Smallest drive determines capacity for all drives.
a|
Recommended to be the same, but not required. Smallest drive determines capacity for all drives.
a|
Minimum number of drives
a|
11
a|
Depends on RAID level. RAID 0 needs 1. RAID 1 or 10 needs 2 (requires an even number). RAID 5 minimum is 3. RAID 6 minimum is 5.
a|
Maximum number of drives
a|
Up to the maximum limit for the storage array
a|
RAID 1 and 10--up to the maximum limit of the storage array RAID 5, 6--30 drives
a|
Can choose individual drives when creating a volume
a|
No
a|
Yes
a|
Can specify segment size when creating a volume
a|
Yes. 128K supported.
a|
Yes
a|
Can specify I/O characteristics when creating a volume
a|
No
a|
Yes. File system, database, multimedia, and custom supported.
a|
Drive failure protection
a|
Uses preservation capacity on each drive in the pool making reconstruction faster.
a|
Uses a hot spare drive. Reconstruction is limited by the IOPs of the drive.
a|
Warning when reaching capacity limit
a|
Yes. Can set an alert when used capacity reaches a percentage of the maximum capacity.
a|
No
a|
Migration to a different storage array supported
a|
No. Requires that you migrate to a volume group first.
a|
Yes
a|
Dynamic Segment Size (DSS)
a|
No
a|
Yes
a|
Can change RAID level
a|
No
a|
Yes
a|
Volume expansion (increase capacity)
a|
Yes
a|
Yes
a|
Capacity expansion (add capacity)
a|
Yes
a|
Yes
a|
Capacity reduction
a|
Yes
a|
No
|===

[NOTE]
====
Mixed drive types (HDD, SSD) are not supported for either pools or volume groups.
====
