---
permalink: sm-storage/rtv-what-do-i-need-to-know-before-starting-a-remote-storage-import.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, remote, storage, import
summary: "The Remote Storage feature allows you to copy data from a remote storage system to a volume on a local E-Series storage system. Before using this feature, review the following guidelines."
---
= What do I need to know before starting a remote storage import?
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
The Remote Storage feature allows you to copy data from a remote storage system to a volume on a local E-Series storage system. Before using this feature, review the following guidelines.

== Configuration

Before you create the remote storage import, you must complete the following actions and verify the following conditions:

* Ensure that each controller of the local E-Series storage system has an iSCSI connection to the remote storage system.
* On your local E-Series storage system, create a target volume for the import operation. Ensure that the volume has a capacity that is equal to or greater than the source volume, has a block size that matches the source volume, and is not mapped. See link:create-volumes.html[Create volumes].
* Set up the local E-Series storage system as a host on the remote system using its iSCSI Qualified Name (IQN). You can view the IQN from menu:Settings[System > iSCSI settings > Target IQN]. Also, be sure to set the appropriate host type based on the system being used.
* Stop all I/Os, unmount any file systems, and remove any assignments to hosts or applications for the selected volume on the remote storage system.
* Assign the volume to the remote storage system to the newly created local E-Series storage system host.
* Gather the following information from the remote storage system so that the import can be created:
 ** iSCSI Qualified Name (IQN)
 ** iSCSI IP address
 ** The LUN number of the remote storage device, where the source data originates
* Once the import process begins, the entire local destination volume is overwritten with the copied data. Any new data written to the local destination volume is propagated to the volume on the remote storage device after the import is created. Therefore, we recommend that you back up volumes on the remote storage system before starting the import process.

== Import process

The following steps outline the import process.

. Access the System Manager interface, and then go to the *Remote Storage* page. Select *Import* to start a new import creation. For detailed instructions, see link:rtv-import-remote-storage.html[Import remote storage].
+
If you want to perform an offline import, do not map the destination volume until after the import completes.

. Monitor the progress of the import.
+
Once the import starts, the target volume can then be mapped. The time required to complete the import operation depends on the size of the remote storage device (source volume), the priority setting for the import, and the amount of I/O load on both storage systems and their associated volumes.
+
After import completion, the target volume is a duplicate of the source.

. When you are ready to break the mapping relationship, perform a *Disconnect* on the import object from the *Operations In Progress* panel.

Once the import is disconnected, performance of the local destination returns to normal and is no longer impacted by the remote connection.

== Restrictions

The Remote Storage feature has the following restrictions:

* Mirroring must be disabled.
* Destination volume on the E-Series system must not have snapshots.
* Destination volume on the E-Series system must not be mapped to any hosts before the import is started.
* Destination volume on the E-Series system must have resource-provisioning disabled.
* Direct mappings of the remote storage volume to a host or multiple hosts is not supported.
* Web Services Proxy is not supported.
* iSCSI CHAP secrets are not supported.
* SMcli is not supported.
* VMware Datastore is not supported.
* Only one storage system in the relationship/import pair can be upgraded at a time when there is an import pair present.

== Additional information

Further information for the Remote Storage feature is available from the https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf[Remote Storage Technical Report^].
