---
permalink: sm-storage/task_create_host_automatically.html
sidebar: sidebar
keywords: 
summary: 'You can allow the Host Context Agent \(HCA\) to automatically detect the hosts, and then verify that the information is correct. Creating a host is one of the steps required to let the storage array know which hosts are attached to it and to allow I/O access to the volumes.'
---
= Create host automatically
:icons: font
:imagesdir: ../media/

[.lead]
You can allow the Host Context Agent (HCA) to automatically detect the hosts, and then verify that the information is correct. Creating a host is one of the steps required to let the storage array know which hosts are attached to it and to allow I/O access to the volumes.

== Before you begin

The Host Context Agent (HCA) is installed and running on every host connected to the storage array. Hosts with the HCA installed and connected to the storage array are created automatically. To install the HCA, install SANtricity Storage Manager on the host and select the Host option. The HCA is not available on all supported operating systems. If it is not available, you must create the host manually.

== Steps

. Select *Storage* > *Hosts*.
+
The table lists the automatically-created hosts.

. Verify that the information provided by the HCA is correct (name, host type, host port identifiers).
+
If you need to change any of the information, select the host, and then click *View/Edit Settings*.

. (Optional) If you want the automatically-created host to be in a cluster, create a host cluster and add the host or hosts.

== Results

After a host is created automatically, the system displays the following items in the Hosts tile table:

* The host name derived from the system name of the host.
* The host identifier ports that are associated with the host.
* The Host Operating System Type of the host.
