---
permalink: sm-storage/task_create_volumes_hosts_step_1.html
sidebar: sidebar
keywords: 
summary: 'You create volumes to add storage capacity to an application-specific workload, and to make the created volumes visible to a specific host or host cluster. In addition, the volume creation sequence provides options to allocate specific amounts of capacity to each volume you want to create.'
---
= Step 1: Select host for a volume
:icons: font
:imagesdir: ../media/

[.lead]
You create volumes to add storage capacity to an application-specific workload, and to make the created volumes visible to a specific host or host cluster. In addition, the volume creation sequence provides options to allocate specific amounts of capacity to each volume you want to create.

== Before you begin

* Valid hosts or host clusters exist under the *Hosts* tile.
* Host port identifiers have been defined for the host.
* Before creating a DA-enabled volume, the host connection you are planning to use must support DA. If any of the host connections on the controllers in your storage array do not support DA, the associated hosts cannot access data on DA-enabled volumes.

== About this task

Keep these guidelines in mind when you assign volumes:

* A host's operating system can have specific limits on how many volumes the host can access. Keep this limitation in mind when you create volumes for use by a particular host.
* You can define one assignment for each volume in the storage array.
* Assigned volumes are shared between controllers in the storage array.
* The same logical unit number (LUN) cannot be used twice by a host or a host cluster to access a volume. You must use a unique LUN.
* If you want to speed the process for creating volumes, you can skip the host assignment step so that newly created volumes are initialized offline.

[NOTE]
====
Assigning a volume to a host will fail if you try to assign a volume to a host cluster that conflicts with an established assignment for a host in the host clusters.
====

== Steps

. Select *Storage* > *Volumes*.
. Select *Create* > *Volume*.
+
The Create Volumes dialog box appears.

. From the drop-down list, select a specific host or host cluster to which you want to assign volumes, or choose to assign the host or host cluster at a later time.
. To continue the volume creation sequence for the selected host or host cluster, click *Next*, and go to xref:task_create_volumes_storage_step_2.adoc[Step 2: Select a workload for a volume].
+
The Select Workload dialog box appears.
