---
permalink: sm-storage/what-is-a-snapshot-image.html
sidebar: sidebar
keywords: 
summary: 'A snapshot image is a logical copy of volume content, captured at a particular point in time. Snapshot images use minimal storage space.'
---
= What is a snapshot image?
:icons: font
:imagesdir: ../media/

[.lead]
A snapshot image is a logical copy of volume content, captured at a particular point in time. Snapshot images use minimal storage space.

Snapshot image data is stored as follows:

* When a snapshot image is created, it exactly matches the base volume. After the snapshot is taken, when the first write request occurs for any block or set of blocks on the base volume, the original data is copied to the snapshot reserved capacity before the new data is written to the base volume.
* Subsequent snapshots include only data blocks that have changed since the first snapshot image was created. Each subsequent copy-on-write operation saves original data that is about to be overwritten on the base volume to the snapshot reserved capacity before the new data is written to the base volume.
