---
permalink: sm-storage/what-do-i-need-to-know-about-increasing-reserved-capacity.html
sidebar: sidebar
keywords: 
summary: 'Typically, you should increase capacity when you receive a warning that the reserved capacity is in danger of becoming full. You can increase reserved capacity only in increments of 8 GiB.'
---
= What do I need to know about increasing reserved capacity?
:icons: font
:imagesdir: ../media/

[.lead]
Typically, you should increase capacity when you receive a warning that the reserved capacity is in danger of becoming full. You can increase reserved capacity only in increments of 8 GiB.

* You must have sufficient free capacity in the pool or volume group so it can be expanded if necessary.
+
If no free capacity exists on any pool or volume group, you can add unassigned capacity in the form of unused drives to a pool or volume group.

* The volume in the pool or volume group must have an Optimal status and must not be in any state of modification.
* Free capacity must exist in the pool or volume group that you want to use to increase capacity.
* You cannot increase reserved capacity for a snapshot volume that is read-only. Only snapshot volumes that are read-write require reserved capacity.

For snapshot operations, reserved capacity is typically 40 percent of the base volume. For asynchronous mirroring operations reserved capacity is typically 20 percent of the base volume. Use a higher percentage if you believe the base volume will undergo many changes or if the estimated life expectancy of a storage object's copy service operation will be very long.
