---
permalink: sm-storage/what-is-a-snapshot-volume-and-when-does-it-need-reserved-capacity.html
sidebar: sidebar
keywords: 
summary: 'A snapshot volume allows the host to access data in the snapshot image. The snapshot volume contains its own reserved capacity, which saves any modifications to the base volume without affecting the original snapshot image. Snapshot images are not read- or write-accessible to hosts. If you want to read or write to snapshot data, create a snapshot volume and assign it to a host.'
---
= What is a snapshot volume and when does it need reserved capacity?
:icons: font
:imagesdir: ../media/

[.lead]
A snapshot volume allows the host to access data in the snapshot image. The snapshot volume contains its own reserved capacity, which saves any modifications to the base volume without affecting the original snapshot image. Snapshot images are not read- or write-accessible to hosts. If you want to read or write to snapshot data, create a snapshot volume and assign it to a host.

You can create two types of snapshot volumes. The type of snapshot volume determines if it uses reserved capacity.

* *Read-only* -- A snapshot volume that is created as read-only provides a host application with read access to a copy of the data contained in the snapshot image. A read-only snapshot volume does not use reserved capacity.
* *Read-write* -- A snapshot volume that is created as read-write allows you to make changes to the snapshot volume without affecting the referenced snapshot image. A read-write snapshot volume uses reserved capacity to store these changes. You can convert a read-only snapshot volume to read-write at any time.
