---
permalink: sm-storage/what-does-the-cpu-graph-show.html
sidebar: sidebar
keywords: 
summary: 'The CPU graph displays processing capacity statistics for each controller \(controller A and controller B\). CPU is an abbreviation for central processing unit. On the Home page, this graph displays statistics for the storage array. On the Physical View tab of the Performance tile, this graph displays statistics for the storage array and drives.'
---
= What does the CPU graph show?
:icons: font
:imagesdir: ../media/

[.lead]
The CPU graph displays processing capacity statistics for each controller (controller A and controller B). CPU is an abbreviation for _central processing unit_. On the Home page, this graph displays statistics for the storage array. On the Physical View tab of the Performance tile, this graph displays statistics for the storage array and drives.

The CPU graph shows the percentage of CPU processing capacity being used against operations on the array. Even when no external I/O is occurring, the CPU utilization percentage can be non-zero because the storage operating system might be doing background operations and monitoring. Hover your cursor over a point on the graph to view a percentage of processing capability being used at that point in time.
