---
permalink: sm-storage/why-use-snapshot-images.html
sidebar: sidebar
keywords: 
summary: 'You can use snapshots to protect against and allow recovery from accidental or malicious loss or corruption of data.'
---
= Why use snapshot images?
:icons: font
:imagesdir: ../media/

[.lead]
You can use snapshots to protect against and allow recovery from accidental or malicious loss or corruption of data.

Select a base volume or a group of base volumes, called a snapshot consistency group, and then capture snapshot images in one or more of the following ways:

* You can create a snapshot image of a single base volume or a snapshot consistency group consisting of multiple base volumes.
* You can take snapshots manually or create a schedule for a base volume or snapshot consistency group to automatically capture periodic snapshot images.
* You can create a host-accessible snapshot volume of a snapshot image.
* You can perform a rollback operation to restore a snapshot image.

The system retains multiple snapshot images as restore points you can use to roll back to known good data sets at specific points in time. The ability to roll back provides protection against accidental deletion of data and data corruption.
