---
permalink: sm-storage/why-would-i-create-a-snapshot-consistency-group.html
sidebar: sidebar
keywords: 
summary: 'You create a snapshot consistency group when you want to make sure snapshot images are taken on multiple volumes at the same time. For example, a database made up of multiple volumes that need to stay consistent for recovery purposes would require a snapshot consistency group to collect coordinated snapshots of all volumes and use them to restore the entire database.'
---
= Why would I create a snapshot consistency group?
:icons: font
:imagesdir: ../media/

[.lead]
You create a snapshot consistency group when you want to make sure snapshot images are taken on multiple volumes at the same time. For example, a database made up of multiple volumes that need to stay consistent for recovery purposes would require a snapshot consistency group to collect coordinated snapshots of all volumes and use them to restore the entire database.

The volumes included in a snapshot consistency group are called member volumes.

You can perform the following snapshot operations on a snapshot consistency group:

* Create a snapshot image of a snapshot consistency group to get simultaneous images of the member volumes.
* Create a schedule for the snapshot consistency group to automatically capture periodic simultaneous images of the member volumes.
* Create a host-accessible snapshot volume of a snapshot consistency group image.
* Perform a rollback operation for a snapshot consistency group.
