---
permalink: sm-mirroring/asynchronous-mirroring-why-dont-i-see-all-the-volumes-on-the-remote-storage-array.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, volumes, remote, storage, array, mirrored, pair,
summary: "When you are selecting a secondary volume on the remote storage array, a list shows all the eligible volumes for that mirrored pair."
---
= Asynchronous mirroring - Why don't I see all the volumes on the remote storage array?
:icons: font
:imagesdir: ../media/

[.lead]
When you are selecting a secondary volume on the remote storage array, a list shows all the eligible volumes for that mirrored pair.

Any volumes that are not eligible to be used, do not display in that list. Volumes might not be eligible for any of the following reasons:

* The volume is not optimal.
* The volume is already participating in a mirroring relationship.
* The thin volume attributes between the primary volume and the secondary volume do not match.
* If you are using Data Assurance (DA), the primary volume and the secondary volume must have the same DA settings.
 ** If the primary volume is DA enabled, the secondary volume must be DA enabled.
 ** If the primary volume is not DA enabled, the secondary volume must not be DA enabled.
