---
permalink: sm-mirroring/concept_asynchronous_mirroring_what_do_i_need_to_know_before_creating_a_mirrored_pair.html
sidebar: sidebar
keywords: 
summary: 'You configure mirrored pairs in the Unified Manager interface, and then manage the pairs in System Manager.'
---
= Asynchronous mirroring - What do I need to know before creating a mirrored pair?
:icons: font
:imagesdir: ../media/

[.lead]
You configure mirrored pairs in the Unified Manager interface, and then manage the pairs in System Manager.

Before creating a mirrored pair, follow these guidelines.

* You must have two storage arrays.
* Each storage array must have two controllers.
* Each controller in both the primary array and secondary array must have an Ethernet management port configured and must be connected to your network.
* Your local and remote storage arrays are connected through a Fibre Channel fabric or iSCSI interface.
* The storage arrays have a minimum firmware version of 7.84. (They can each run different OS versions.)
* You must know the password for the local and remote storage arrays.
* You must have enough free capacity on the remote storage array to create a secondary volume equal to or greater than the primary volume that you want to mirror.
* You have installed the Web Services Proxy and Unified Manager. Mirrored pairs are configured in the Unified Manager interface.
* The two storage arrays are discovered in Unified Manager.
* Your storage array must contain at least one mirror consistency group. You create a consistency group in Unified Manager in the Create Mirrored Pairs wizard.
