---
permalink: sm-mirroring/concept_how_does_asynchronous_mirroring_differ_from_synchronous_mirroring_sync.html
sidebar: sidebar
keywords: 
summary: 'The Asynchronous Mirroring feature differs from the Synchronous Mirroring feature in one essential way: it captures the state of the source volume at a particular point in time and copies just the data that has changed since the last image capture.'
---
= How does asynchronous mirroring differ from synchronous mirroring?
:icons: font
:imagesdir: ../media/

[.lead]
The Asynchronous Mirroring feature differs from the Synchronous Mirroring feature in one essential way: it captures the state of the source volume at a particular point in time and copies just the data that has changed since the last image capture.

With synchronous mirroring, the state of the primary volume is not captured at some point in time, but rather reflects all changes that were made on the primary volume to the secondary volume. The secondary volume is identical to the primary volume at every moment because, with this type of mirror, each time a write is done to the primary volume, a write is done to the secondary volume. The host does not receive an acknowledgment that the write was successful until the secondary volume is successfully updated with the changes that were made on the primary volume.

With asynchronous mirroring, the remote storage array is not fully synchronized with the local storage array, so if the application needs to transition to the remote storage array due to a loss of the local storage array, some transactions could be lost.

Comparison between mirroring features

|===
| Asynchronous Mirroring| Synchronous Mirroring
a|
*Replication method*
a|

* *Point-in-Time*
+
Mirroring is done on demand or automatically according to a user-defined schedule. Schedules can be defined at the granularity of minutes. The minimum time between syncs is 10 minutes.

a|

* *Continuous*
+
Mirroring is automatically executed continuously, copying data from every host write.

a|
*Reserved capacity*
a|

* *Multiple*
+
A reserved capacity volume is required for each mirrored pair.

a|

* *Single*
+
Single reserved capacity volume is required for all mirrored volumes.

a|
*Communication*
a|

* *iSCSI and Fibre Channel*
+
Supports iSCSI and Fibre Channel interfaces between storage arrays.

a|

* *Fibre Channel*
+
Supports only Fibre Channel interfaces between storage arrays.

a|
*Distance*
a|

* *Unlimited*
+
Support for virtually unlimited distances between the local storage array and the remote storage array, with the distance typically limited only by the capabilities of the network and the channel extension technology.

a|

* *Restricted*
+
Typically must be within about 10 km (6.2 miles), of the local storage array to meet the latency and application performance requirements.

|===
