---
permalink: sm-mirroring/concept_what_impact_does_synchronization_priority_have_on_synchronization_rates.html
sidebar: sidebar
keywords: 
summary: 'The synchronization priority defines how much processing time is allocated for synchronization activities relative to system performance.'
---
= What impact does synchronization priority have on synchronization rates?
:icons: font
:imagesdir: ../media/

[.lead]
The synchronization priority defines how much processing time is allocated for synchronization activities relative to system performance.

The controller owner of the primary volume performs this operation in the background. At the same time, the controller owner processes local I/O writes to the primary volume and associated remote writes to the secondary volume. Because the resynchronization diverts controller processing resources from I/O activity, resynchronization can have a performance impact to the host application.

Keep these guidelines in mind to help you determine how long a synchronization priority might take and how the synchronization priorities can affect system performance.

About synchronization priority rates

These priority rates are available:

* Lowest
* Low
* Medium
* High
* Highest

The lowest priority rate supports system performance, but the resynchronization takes longer. The highest priority rate supports resynchronization, but system performance might be compromised.

These guidelines roughly approximate the differences between the priorities.

|===
| Priority rate for full synchronization| Time elapsed compared to highest synchronization rate
a|
Lowest
a|
Approximately eight times as long as at the highest priority rate.
a|
Low
a|
Approximately six times as long as at the highest priority rate.
a|
Medium
a|
Approximately three-and-a-half times as long as at the highest priority rate.
a|
High
a|
Approximately twice as long as at the highest priority rate.
|===
Volume size and host I/O rate loads affect the synchronization time comparisons.
