---
permalink: sm-mirroring/task_change_synchronization_settings_for_a_mirrored_pair.html
sidebar: sidebar
keywords: 
summary: 'You can change the synchronization priority and resynchronization policy that the mirrored pair uses to complete the resynchronization operation after a communication interruption.'
---
= Change synchronization settings for a mirrored pair
:icons: font
:imagesdir: ../media/

[.lead]
You can change the synchronization priority and resynchronization policy that the mirrored pair uses to complete the resynchronization operation after a communication interruption.

== About this task

You can edit the synchronization settings for a mirrored pair only on the storage array that contains the primary volume.

== Steps

. Select *Storage* > *Synchronous Mirroring*.
. Select the mirrored pair that you want to edit, and then select *More* > *Edit settings*.
+
The system displays the View/Edit Settings dialog box.

. Use the slider bar to edit the synchronization priority.
+
The synchronization priority determines how much of the system resources are used to complete the resynchronization operation after a communication interruption as compared to service I/O requests.
+
More about synchronization rates
+
There are five synchronization priority rates:

 ** Lowest
 ** Low
 ** Medium
 ** High
 ** Highest
If the synchronization priority is set to the lowest rate, I/O activity is prioritized, and the resynchronization operation takes longer. If the synchronization priority is set to the highest rate, the resynchronization operation is prioritized, but I/O activity for the storage array might be affected.

. Edit the resynchronization policy as appropriate.
+
You can resynchronize the mirrored pairs on the remote storage array either manually or automatically.

 ** *Manual*(the recommended option) -- Select this option to require synchronization to be manually resumed after communication is restored to a mirrored pair. This option provides the best opportunity for recovering data.
 ** *Automatic*-- Select this option to start resynchronization automatically after communication is restored to a mirrored pair.

. Select *Save*.
