---
permalink: sm-mirroring/task_re_synchronize_mirror_consistency_group_manually.html
sidebar: sidebar
keywords: 
summary: 'You can manually start re-synchronization for all mirrored pairs within a mirror consistency group.'
---
= Re-synchronize mirror consistency group manually
:icons: font
:imagesdir: ../media/

[.lead]
You can manually start re-synchronization for all mirrored pairs within a mirror consistency group.

== Steps

. Select *Storage* > *Asynchronous Mirroring*.
. Select the *Mirror Consistency Groups* tab.
+
The Mirror Consistency Group table appears and displays all the mirror consistency groups associated with the storage array.

. Select the mirror consistency group that you want to re-synchronize, and then select *More* > *Manually resynchronize*.
+
The system displays a confirmation.

. Select *Yes* to confirm.

== Results

The system performs the following actions:

* Initiates re-synchronization of data on all of the mirrored pairs within the selected mirror consistency group.
* Updates modified data from the local storage array to the remote storage array.
