---
permalink: sm-mirroring/what-do-i-need-to-know-before-increasing-my-reserved-capacity-on-a-mirrored-pair-volume.html
sidebar: sidebar
keywords: 
summary: 'Typically, you should increase reserved capacity when you receive a warning that the reserved capacity for a mirrored pair is becoming full. You can increase reserved capacity only in increments of 8 GiB.'
---
= What do I need to know before increasing my reserved capacity on a mirrored pair volume?
:icons: font
:imagesdir: ../media/

[.lead]
Typically, you should increase reserved capacity when you receive a warning that the reserved capacity for a mirrored pair is becoming full. You can increase reserved capacity only in increments of 8 GiB.

For asynchronous mirroring operations, reserved capacity is typically 20 percent of the base volume. Choose a larger capacity for reserved capacity if one or both of these conditions exist:

* You intend to keep the mirrored pair for a long period of time.
* A large percentage of data blocks will change on the primary volume due to heavy I/O activity. Use historical performance data or other operating system utilities to help you determine typical I/O activity to the primary volume.

You can increase the reserved capacity for a mirrored pair by performing one of these actions:

* Adjust the capacity percentage for a mirrored pair volume by selecting *Storage* > *Pools and Volumes Groups* and then clicking the *Reserved Capacity* tab.
* Create a new volume using free capacity that is available on a pool or volume group.
+
If no free capacity exists on any pool or volume group, you can add unconfigured capacity in the form of unused drives to a pool or volume group.
