---
permalink: sm-mirroring/why-cant-i-increase-reserved-capacity-with-my-requested-amount.html
sidebar: sidebar
keywords: 
summary: 'You can increase reserved capacity only in increments of 4 GiB.'
---
= Why can't I increase reserved capacity with my requested amount?
:icons: font
:imagesdir: ../media/

[.lead]
You can increase reserved capacity only in increments of 4 GiB.

Review the following guidelines:

* You must have sufficient free capacity in the pool or volume group so it can be expanded if necessary.
+
If no free capacity exists on any pool or volume group, you can add unassigned capacity in the form of unused drives to a pool or volume group.

* The volume in the pool or volume group must have an Optimal status and must not be in any state of modification.
* Free capacity must exist in the pool or volume group that you want to use to increase capacity.

For asynchronous mirroring operations reserved capacity is typically 20 percent of the base volume. Use a higher percentage if you believe the base volume will undergo many changes or if the estimated life expectancy of a storage object's copy service operation will be very long.
