---
permalink: sm-mirroring/why-cant-i-access-my-chosen-mirroring-feature.html
sidebar: sidebar
keywords: can't, access, my, chosen, mirroring, feature, configured, unified, manager, interface,
summary: "Mirroring is configured in the Unified Manager interface."
---
= Why can't I access my chosen mirroring feature?
:icons: font
:imagesdir: ../media/

[.lead]
Mirroring is configured in the Unified Manager interface.

To enable and configure mirroring between two arrays, verify the following:

* The Web Services Proxy service must be running. (Unified Manager is installed on a host system along with the Web Services Proxy.)
* Unified Manager must be running on your local host through an HTTPS connection.
* The two storage arrays you want to use for mirroring must be discovered in Unified Manager.
* Unified Manager must have valid SSL certificates for the storage arrays. You can accept a self-signed certificate or install CA-signed certificates from Unified Manager.

For more information about requirements, see the online help for Unified Manager.

[NOTE]
====
Mirroring is not available on the EF600 or EF300 storage array.
====
