---
permalink: sm-mirroring/why-would-i-update-my-remote-storage-arrays-ip-address.html
sidebar: sidebar
keywords: 
summary: 'You update your remote storage array’s IP address when the IP address of an iSCSI port changes and the local storage array is unable to communicate with the remote storage array.'
---
= Why would I update my remote storage array's IP address?
:icons: font
:imagesdir: ../media/

[.lead]
You update your remote storage array's IP address when the IP address of an iSCSI port changes and the local storage array is unable to communicate with the remote storage array.

More about the remote IP address

When establishing an asynchronous mirroring relationship with an iSCSI connection, both the local and the remote storage arrays store a record of the IP address of the remote storage array in the asynchronous mirroring configuration. If the IP address of an iSCSI port changes, the remote storage array that is attempting to use that port encounters a communication error.

The storage array with the changed IP address sends a message to each remote storage array associated with the mirror consistency groups that are configured to mirror over an iSCSI connection. Storage arrays that receive this message automatically update their remote-target IP address.

If the storage array with the changed IP address is unable to send its inter-array message to a remote storage array, the system sends you an alert of the connectivity issue. Use the *Update Remote IP Address* option to re-establish connection with the local storage array.
