---
permalink: sm-interface/concept_setup_wizard_terminology.html
sidebar: sidebar
keywords: 
summary: 'Learn how the Setup wizard terms apply to your storage array.'
---
= Setup wizard terminology
:icons: font
:imagesdir: ../media/

[.lead]
Learn how the Setup wizard terms apply to your storage array.

|===
| Term

| Description

a|
Application

a|
An application is a software program, such as Microsoft SQL Server or Microsoft Exchange.

a|
Alert

a|
Alerts notify administrators about important events that occur on the storage arrays. Alerts can be sent via email, SNMP traps, or syslog.

a|
AutoSupport

a|
The AutoSupport feature monitors the health of a storage array and sends automatic dispatches to technical support.

a|
Hardware

a|
The storage system hardware includes storage arrays, controllers, and drives.

a|
Host

a|
A host is a server that sends I/O to a volume on a storage array.

a|
Object

a|
An object is any logical or physical storage component. Logical objects include volume groups, pools, and volumes. Physical objects include the storage array, array controllers, hosts, and drives.

a|
Pool

a|
A pool is a set of drives that is logically grouped. You can use a pool to create one or more volumes accessible to a host. (You create volumes from either a pool or a volume group.)
a|
Volume

a|
A volume is a container in which applications, databases, and file systems store data. It is the logical component created for the host to access storage on the storage array.

A volume is created from the capacity available in a pool or a volume group. A volume has a defined capacity. Although a volume might consist of more than one drive, a volume appears as one logical component to the host.

a|
Volume group

a|
A volume group is a container for volumes with shared characteristics. A volume group has a defined capacity and RAID level. You can use a volume group to create one or more volumes accessible to a host. (You create volumes from either a volume group or a pool.)

a|
Workload

a|
A workload is a storage object that supports an application. You can define one or more workloads, or instances, per application. For some applications, the system configures the workload to contain volumes with similar underlying volume characteristics. These volume characteristics are optimized based on the type of application the workload supports. For example, if you create a workload that supports a Microsoft SQL Server application and then subsequently create volumes for that workload, the underlying volume characteristics are optimized to support Microsoft SQL Server.

|===
