---
permalink: sm-interface/concept_administrator_password_protection.html
sidebar: sidebar
keywords: 
summary: 'You must configure the storage array with an administrator password to protect it from unauthorized access.'
---
= Administrator password protection
:icons: font
:imagesdir: ../media/

[.lead]
You must configure the storage array with an administrator password to protect it from unauthorized access.

== Setting an administrator password

Setting an administrator password for your storage array protects it from users who unknowingly or maliciously run destructive commands. You are required to set an administrator password when you start System Manager for the first time.

There is one administrator password that is shared among all users. Any user who has this password can make configuration changes to the storage array, such as adding, changing, or removing objects or settings.

== Entering your password

The system prompts you for the password only once during a single management session. A session times out after 20 minutes of inactivity, at which time, you must enter the password again.

If another user managing the same storage array from another management client changes the password while your session is in progress, you are prompted for a password the next time you attempt a configuration operation or a view operation.

For security reasons, you can attempt to enter a password only five times before the storage array enters a "lockout" state. In this state, the storage array will reject subsequent password attempts. You must wait 10 minutes for the storage array to reset to a "normal" state before you try to enter a password again.

== Removing drives with password protection

The password is stored on a reserved area of each drive on the storage array. If you remove all drives from a storage array, its password will no longer work. To correct this condition, re-install one of the original drives to the storage array.

== Removing password protection

If you no longer want to have commands password-protected, enter the current administrator password, and leave the new password text boxes blank.

[NOTE]
====
Running configuration commands on a storage array can cause serious damage, including data loss. For this reason, you should always set an administrator password for your storage array. Use a long administrator password with at least 15 alphanumeric characters to increase security.
====
