---
permalink: sm-interface/what-is-a-workload.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, workload
summary: "For some applications in your network, such as SQL Server or Exchange, you can define a workload that optimizes storage for that application."
---
= What is a workload?
:icons: font
:imagesdir: ../media/

[.lead]
For some applications in your network, such as SQL Server or Exchange, you can define a workload that optimizes storage for that application.

A workload is a storage object that supports an application. You can define one or more workloads, or instances, per application. For some applications, the system configures the workload to contain volumes with similar underlying volume characteristics. These volume characteristics are optimized based on the type of application the workload supports. For example, if you create a workload that supports a Microsoft SQL Server application and then subsequently create volumes for that workload, the underlying volume characteristics are optimized to support Microsoft SQL Server.

During volume creation, the system prompts you to answer questions about a workload's use. For example, if you are creating volumes for Microsoft Exchange, you are asked how many mailboxes you need, what your average mailbox capacity requirements are, and how many copies of the database you want. The system uses this information to create an optimal volume configuration for you, which can be edited as needed.
