---
permalink: sm-hardware/allow-remote-login.html
sidebar: sidebar
keywords: 
summary: 'Remote login lets users from outside of the local area network start an SSH session and change settings on the controller.'
---
= Allow remote login
:icons: font
:imagesdir: ../media/

[.lead]
Remote login lets users from outside of the local area network start an SSH session and change settings on the controller.

== About this task

[NOTE]
====
*Security risk* -- For security reasons, enable remote login for use only by technical support.
====

== Steps

. Select *Hardware*.
. If the graphic shows the drives, click *Show back of shelf*.
+
The graphic changes to show the controllers instead of the drives.

. Click the controller for which you want to enable remote login.
+
The controller's context menu appears.

. Select *Change remote login*, and confirm that you want to perform the operation.

== Results

After technical support is finished troubleshooting, follow this same procedure to disable remote login. Disabling remote login terminates any current SSH sessions and rejects any new login requests.
