---
permalink: sm-hardware/concept_what_are_battery_learn_cycles.html
sidebar: sidebar
keywords: 
summary: 'A learn cycle is an automatic cycle for calibrating the smart battery gauge.'
---
= What are battery learn cycles?
:icons: font
:imagesdir: ../media/

[.lead]
A learn cycle is an automatic cycle for calibrating the smart battery gauge.

A learn cycle consists of these phases:

* Controlled battery discharge
* Rest period
* Charge

The batteries are discharged to a predetermined threshold. During this phase, the battery gauge is calibrated.

A learn cycle requires these parameters:

* Fully charged batteries
* No overheated batteries

Learn cycles for duplex controller systems occur simultaneously. For controllers having backup power from more than one battery or set of battery cells, learn cycles occur sequentially.

Learn cycles are scheduled to start automatically at regular intervals, at the same time and on the same day of the week. The interval between cycles is described in weeks.

[NOTE]
====
A learn cycle might take several hours to complete.
====
