---
permalink: sm-hardware/concept_what_is_auto_negotiation.html
sidebar: sidebar
keywords: 
summary: 'Auto-negotiation is the ability of a network interface to automatically coordinate its own connection parameters \(speed and duplex\) with another network interface.'
---
= What is auto-negotiation?
:icons: font
:imagesdir: ../media/

[.lead]
Auto-negotiation is the ability of a network interface to automatically coordinate its own connection parameters (speed and duplex) with another network interface.

Auto-negotiation is usually the preferred setting for configuring management ports; however, if the negotiation fails, mismatched network interface settings can severely impact network performance. In cases where that condition is unacceptable, you should manually set the network interface settings to a correct configuration. Auto-negotiation is performed by the controller's Ethernet management ports. Auto-negotiation is not performed by iSCSI host bus adapters.

[NOTE]
====
If auto-negotiation fails, the controller attempts to establish a connection at 10BASE-T, half-duplex, which is the lowest common denominator.
====
