---
permalink: sm-hardware/place-controller-in-service-mode.html
sidebar: sidebar
keywords: 
summary: 'If you are instructed to do so, you can place a controller in service mode.'
---
= Place controller in service mode
:icons: font
:imagesdir: ../media/

[.lead]
If you are instructed to do so, you can place a controller in service mode.

== Before you begin

* The storage array must have two controllers. The controller that you are not placing in service mode must be online (in the optimal state).
* Make sure that no volumes are in use or that you have a multipath driver installed on all hosts using these volumes.

== About this task

[NOTE]
====
Placing a controller in service mode might significantly reduce performance. Do not place a controller in service mode unless you are instructed to do so by technical support.
====

== Steps

. Select *Hardware*.
. If the graphic shows the drives, click *Show back of shelf*.
+
The graphic changes to show the controllers instead of the drives.

. Click the controller that you want to place into service mode.
+
The controller's context menu appears.

. Select *Place in service mode*, and confirm that you want to perform the operation.
