---
permalink: sm-hardware/turn-on-drive-locator-light.html
sidebar: sidebar
keywords: 
summary: 'From the Hardware page, you can turn on the locator light to find the physical location of a drive in the storage array.'
---
= Turn on drive locator light
:icons: font
:imagesdir: ../media/

[.lead]
From the Hardware page, you can turn on the locator light to find the physical location of a drive in the storage array.

== About this task

You can locate single drives or multiple drives shown on the Hardware page.

== Steps

. Select *Hardware*.
. To locate one or more drives, do one of the following:
 ** *Single drive* -- From the shelf graphic, find the drive you want to physically locate in the array. (If the graphic shows the controllers, click *Show front of shelf*.) Click the drive to display its context menu, and then select *Turn on locator light*.
+
The drive's locator light turns on. When you have physically located the drive, return to the dialog and select *Turn off*.

 ** *Multiple drives* -- In the filter fields, select a physical drive type from the left drop-down list and a logical drive type from the right drop-down list. The number of drives matching your criteria is shown on the far right of the fields. Next, you can either click *Turn on locator lights* or select *Locate all filtered drives* from the context menu. When you have physically located the drives, return to the dialog and select *Turn off*.
