---
permalink: sm-hardware/what-is-a-dhcp-server.html
sidebar: sidebar
keywords: 
summary: 'Dynamic Host Configuration Protocol \(DHCP\) is a protocol that automates the task of assigning an Internet Protocol \(IP\) address.'
---
= What is a DHCP server?
:icons: font
:imagesdir: ../media/

[.lead]
Dynamic Host Configuration Protocol (DHCP) is a protocol that automates the task of assigning an Internet Protocol (IP) address.

Each device that is connected to a TCP/IP network must be assigned a unique IP address. These devices include the controllers in your storage array.

Without DHCP, a network administrator enters these IP addresses manually. With DHCP, when a client needs to start TCP/IP operations, the client broadcasts a request for address information. The DHCP server receives the request, assigns a new address for a specified amount of time called a lease period, and sends the address to the client. With DHCP, a device can have a different IP address each time it connects to the network. In some systems, the IP address for the device can change even while the device is still connected.
