---
permalink: um-manage/concept_why_don_t_i_see_all_the_volumes_on_the_remote_storage_array_um.html
sidebar: sidebar
keywords: 
summary: 'When you are selecting a secondary volume on the remote storage array, a list shows all the eligible volumes for that mirrored pair.'
---
= Why don't I see all the volumes on the remote storage array?
:icons: font
:imagesdir: ../media/

[.lead]
When you are selecting a secondary volume on the remote storage array, a list shows all the eligible volumes for that mirrored pair.

Any volumes that are not eligible to be used, do not display in that list. Volumes may not be eligible for any of the following reasons:

* The volume is a non-standard volume, such as a snapshot volume.
* The volume is not optimal.
* The volume is already participating in a mirroring relationship.
* For asynchronous mirroring, the thin volume attributes between the primary volume and the secondary volume do not match.
* If you are using Data Assurance (DA), the primary volume and the secondary volume must have the same DA settings.
 ** If the primary volume is DA enabled, the secondary volume must be DA enabled.
 ** If the primary volume is not DA enabled, the secondary volume must not be DA enabled.
* For asynchronous mirroring, the primary volume and the secondary volume must have the same Drive Security capabilities.
 ** If the primary volume is FIPS capable, the secondary volume must be FIPS capable.
 ** If the primary volume is FDE capable, the secondary volume must be FDE capable.
 ** If the primary volume is not using Drive Security, the secondary volume must not be using Drive Security.
