---
permalink: um-manage/provide-passwords.html
sidebar: sidebar
keywords: provide, passwords
summary: "You must enter the passwords for the storage arrays that you want to add to your management domain."
---
= Provide passwords
:icons: font
:imagesdir: ../media/

[.lead]
You must enter the passwords for the storage arrays that you want to add to your management domain.

.Before you begin

* The storage array must be correctly set up and configured.
* Storage array passwords must be set up using SANtricity System Manager's Access Management tile.

.Steps

. Enter the password for each storage array you want to add to SANtricity Unified Manager.
. *Optional:* Associate storage arrays to a group: From the drop-down list, select the desired group to associate with the selected storage arrays.
. Click *Finish*.

.After you finish

The storage arrays are added to your management domain and associated with the selected group (if specified).

[NOTE]
====
It can take several minutes for SANtricity Unified Manager to connect to the specified storage arrays.
====
