---
permalink: um-manage/resolve-self-signed-certificates-during-discovery.html
sidebar: sidebar
keywords: resolve, self-signed, certificates, discovery
summary: "As part of the discovery process, the system verifies that the storage arrays are using certificates by a trusted source."
---
= Resolve self-signed certificates during discovery
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
As part of the discovery process, the system verifies that the storage arrays are using certificates by a trusted source.

.Before you begin

* You must be logged in with a user profile that includes Security Admin permissions.

.Steps

. Do one of the following:
 ** If you trust the connections to the discovered storage arrays, continue to the next card in the wizard. The self-signed certificates will be marked as trusted and the storage arrays will be added to SANtricity Unified Manager.
 ** If you do not trust the connections to the storage arrays, select *Cancel* and validate each storage array's security certificate strategy before adding any of them to Unified Manager.
. Click *Next* to proceed to the next step in the wizard.
. Go to xref:resolve-untrusted-certificates-during-discovery.adoc[Resolve untrusted certificates].
