---
permalink: um-manage/step-2-select-the-secondary-volume-um-sync.html
sidebar: sidebar
keywords: 
summary: 'Select the secondary volume that you want to use in the mirror relationship.'
---
= Step 2: Select the secondary volume
:icons: font
:imagesdir: ../media/

[.lead]
Select the secondary volume that you want to use in the mirror relationship.

== Before you begin

* You must have created the secondary volume that you want to use in the synchronous mirror relationship.
* The secondary volume must be a standard volume. It cannot be a thin volume or a snapshot volume.
* The secondary volume should be at least as large as the primary volume.

== About this task

When you select a secondary volume on the remote storage array, the system displays a list of all the eligible volumes for that mirrored pair. Any volumes that are not eligible to be used do not display in that list.

The volume you select will hold the secondary role in the mirror relationship.

== Steps

. Select the remote storage array on which you want to establish a mirror relationship with the local storage array.
+
[NOTE]
====
If your remote storage array is password protected, the system prompts for a password.
====

 ** Storage arrays are listed by their storage array name. If you have not named a storage array, it will be listed as "unnamed."
 ** If the storage array you want to use is not in the list, make sure it has been discovered in Unified Manager.

. From the list of eligible volumes, select a volume that you want to use as the secondary volume in the mirror.
+
[NOTE]
====
If a secondary volume is chosen with a capacity that is larger than the primary volume, the usable capacity is restricted to the size of the primary volume.
====

. Click *Next* and go to link:step-3-select-sync-settings-um-sync.md#[Step 3: Select synchronization settings].
