---
permalink: um-manage/step-3-select-the-secondary-volume-um-async.html
sidebar: sidebar
keywords: 
summary: 'Select the secondary volume that you want to use in the mirror relationship and allocate its reserved capacity.'
---
= Step 3: Select the secondary volume
:icons: font
:imagesdir: ../media/

[.lead]
Select the secondary volume that you want to use in the mirror relationship and allocate its reserved capacity.

== Before you begin

* You must have created the secondary volume on the remote storage array that you want to use in the asynchronous mirror relationship.
* The secondary volume must be at least as large as the primary volume.

== About this task

When you select a secondary volume on the remote storage array, the system displays a list of all the eligible volumes for that mirrored pair. Any volumes that are not eligible to be used do not display in that list.

Any volumes you add to the mirror consistency group on the remote storage array will hold the secondary role in the mirror relationship.

== Steps

. From the list of eligible volumes, select a volume that you want to use as the secondary volume in the mirrored pair, and then click *Next* to allocate the reserved capacity.
. From the list of eligible candidates, select reserved capacity for the secondary volume.
+
Keep the following guidelines in mind:

 ** The default setting for reserved capacity is 20% of the capacity of the base volume, and usually this capacity is sufficient. If you change the percentage, click *Refresh Candidates*.
 ** The capacity needed varies, depending on the frequency and size of I/O writes to the primary volume and how long you need to keep the capacity.
 ** In general, choose a larger capacity for reserved capacity if one or both of these conditions exist:
  *** You intend to keep the mirrored pair for a long period of time.
  *** A large percentage of data blocks will change on the primary volume due to heavy I/O activity. Use historical performance data or other operating system utilities to help you determine typical I/O activity to the primary volume.

. Select *Finish* to complete the asynchronous mirroring sequence.

== Results

Unified Manager performs the following actions:

* Begins initial synchronization between the local storage array and the remote storage array.
* If the volume being mirrored is a thin volume, only the provisioned blocks (allocated capacity rather than reported capacity) are transferred to the secondary volume during the initial synchronization. This reduces the amount of data that must be transferred to complete the initial synchronization.
* Creates the reserved capacity for the mirrored pair on the local storage array and on the remote storage array.
