---
permalink: um-manage/step-3-select-sync-settings-um-sync.html
sidebar: sidebar
keywords: 
summary: 'Select the settings that determine how data is synchronized after a communication interruption.'
---
= Step 3: Select synchronization settings
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
Select the settings that determine how data is synchronized after a communication interruption.

== About this task

You can set the priority at which the controller owner of the primary volume resynchronizes data with the secondary volume after a communication interruption. You must also select the resynchronization policy, either manual or automatic.

== Steps

. Use the slider bar to set the synchronization priority.
+
The synchronization priority determines how much of the system resources are used to complete initial synchronization and the resynchronization operation after a communication interruption as compared to service I/O requests.
+
The priority set on this dialog applies to both the primary volume and the secondary volume. You can modify the rate on the primary volume at a later time by going to System Manager and selecting menu:Storage[Synchronous Mirroring > More > Edit Settings].
+
There are five synchronization priority rates:

 ** Lowest
 ** Low
 ** Medium
 ** High
 ** Highest
If the synchronization priority is set to the lowest rate, I/O activity is prioritized, and the resynchronization operation takes longer. If the synchronization priority is set to the highest rate, the resynchronization operation is prioritized, but I/O activity for the storage array might be affected.

. Choose whether you want to resynchronize the mirrored pairs on the remote storage array either manually or automatically.
 ** *Manual*(the recommended option) -- Select this option to require synchronization to be manually resumed after communication is restored to a mirrored pair. This option provides the best opportunity for recovering data.
 ** *Automatic*-- Select this option to start resynchronization automatically after communication is restored to a mirrored pair.
To manually resume synchronization, go to System Manager and select menu:Storage[Synchronous Mirroring], highlight the mirrored pair in the table, and select *Resume* under *More*.
. Click *Finish* to complete the synchronous mirroring sequence.

== Results

Once mirroring is activated, the system performs the following actions:

* Begins initial synchronization between the local storage array and the remote storage array.
* Sets the synchronization priority and resynchronization policy.
* Reserves the highest-numbered port of the controller's HIC for mirror data transmission.
+
I/O requests received on this port are accepted only from the remote preferred controller owner of the secondary volume in the mirrored pair. (Reservations on the primary volume are allowed.)

* Creates two reserved capacity volumes, one for each controller, which are used for logging write information to recover from controller resets and other temporary interruptions.
+
The capacity of each volume is 128 MiB. However, if the volumes are placed in a pool, 4 GiB will be reserved for each volume.

== After you finish

Go to System Manager and select *Home* > *View Operations in Progress* to view the progress of the synchronous mirroring operation. This operation can be lengthy and could affect system performance.
