---
permalink: um-manage/task_enter_network_address.html
sidebar: sidebar
keywords: 
summary: 'You enter a network address range to search across the local sub-network. Any storage array successfully reached appears on the Discover page and might be added to your management domain.'
---
= Enter network address
:icons: font
:imagesdir: ../media/

[.lead]
You enter a network address range to search across the local sub-network. Any storage array successfully reached appears on the Discover page and might be added to your management domain.

== About this task

If you need to stop the discovery operation for any reason, click *Stop Discovery*.

== Steps

. From the *Manage* page, select *Add/Discover*.
+
The Add/Discover storage arrays dialog appears.

. Select the *Discover all storage arrays within a network range* radio button.
. Enter the starting network address and ending network address to search across your local sub-network, and then click *Start Discovery*.
+
The discovery process starts. This discovery process can take several minutes to complete. The table on the *Discover* page is populated as the storage arrays are discovered.
+
[NOTE]
====
If no manageable arrays are discovered, verify that the storage arrays are properly connected to your network and their assigned addresses are within range. Click *New Discovery Parameters* to return to the *Add/Discover* page.
====

. Review the list of discovered storage arrays.
. Select the checkbox next to any storage array that you want to add to your management domain, and then click *Next*.
+
SANtricity Unified Manager performs a credential check on each array you are adding to the management domain. You might need to resolve any self-signed certificates and untrusted certificates associated with that array.

. Click *Next* to proceed to the next step in the wizard.
. Go to xref:task_resolve_self_signed_certificates_during_discovery.adoc[Resolve self-signed certificates].
