---
permalink: um-manage/why-dont-i-see-all-my-volumes-um.html
sidebar: sidebar
keywords: SANtricity, Unified Manager, E-Series, volumes missing
summary: "When you are selecting a primary volume for a mirrored pair, a list shows all the eligible volumes."
---
= Why don't I see all my volumes?
:icons: font
:imagesdir: ../media/

[.lead]
When you are selecting a primary volume for a mirrored pair, a list shows all the eligible volumes. 

Any volumes that are not eligible to be used do not display in that list. Volumes might not be eligible for any of the following reasons:

* The volume is not optimal.
* The volume is already participating in a mirroring relationship.
* For synchronous mirroring, the primary and secondary volumes in a mirrored pair must be standard volumes. They cannot be thin volumes or snapshot volumes.
* For asynchronous mirroring, thin volumes must have auto-expansion enabled.

NOTE: For EF600 and EF300 controllers, the primary and secondary volumes of an asynchronous mirrored pair must match the same protocol, tray level, segment size, security type, and RAID level. Non-eligible asynchronous mirrored pairs will not appear in the list of available volumes.