---
permalink: um-manage/why-would-i-change-this-percentage-um.html
sidebar: sidebar
keywords: SANtricity, Unified Manager, E-Series, change, percentage
summary: "Reserved capacity is typically 20 percent of the base volume for asynchronous mirroring operations. Usually this capacity is sufficient."
---
= Why would I change this percentage?
:icons: font
:imagesdir: ../media/

[.lead]
Reserved capacity is typically 20 percent of the base volume for asynchronous mirroring operations. Usually this capacity is sufficient.

The capacity needed varies, depending on the frequency and size of I/O writes to the base volume and how long you intend to use the storage object's copy service operation. In general, choose a larger percentage for reserved capacity if one or both of these conditions exist:

* If the lifespan of a particular storage object's copy service operation will be very long.
* If a large percentage of data blocks will change on the base volume due to heavy I/O activity. Use historical performance data or other operating system utilities to help you determine typical I/O activity to the base volume.
