---
permalink: sm-settings/concept_what_else_do_i_need_to_do_to_configure_or_diagnose_nvme_over_infiniband.html
sidebar: sidebar
keywords: 
summary: 'The following table lists the System Manager functions that you can use to configure and manage NVMe over InfiniBand sessions.'
---
= What else do I need to do to configure or diagnose NVMe over InfiniBand?
:icons: font
:imagesdir: ../media/

[.lead]
The following table lists the System Manager functions that you can use to configure and manage NVMe over InfiniBand sessions.

[NOTE]
====
The NVMe over InfiniBand settings are available only if your storage array's controller includes an NVMe over InfiniBand port.
====

== Configure and diagnose NVMe over InfiniBand

|===
| Action| Location
a|
Configure NVMe over InfiniBand ports
a|

. Select *Hardware*.
. Select *Show back of shelf*.
. Select a controller.
. Select *Configure NVMe over InfiniBand ports*.

or

. Select *Settings* > *System*.
. Scroll down to *NVMe over InfiniBand settings*, and then select *Configure NVMe over InfiniBand Ports*.

a|
View NVMe over InfiniBand statistics
a|

. Select *Settings* > *System*.
. Scroll down to *NVMe over InfiniBand settings*, and then select *View NVMe over Fabrics Statistics*.

|===
