---
permalink: sm-settings/concept_what_do_i_need_to_know_about_validating_the_security_key.html
sidebar: sidebar
keywords: 
summary: 'After creating a security key, you should validate the key file to make sure it is not corrupt.'
---
= What do I need to know about validating the security key?
:icons: font
:imagesdir: ../media/

[.lead]
After creating a security key, you should validate the key file to make sure it is not corrupt.

If the validation fails, do the following:

* If the security key identifier does not match the identifier on the controller, locate the correct security key file and then try the validation again.
* If the controller cannot decrypt the security key for validation, you might have incorrectly entered the pass phrase. Double-check the pass phrase, re-enter it if necessary, and then try the validation again. If the error message appears again, select a backup of the key file (if available) and re-try validation.
* If you still cannot validate the security key, the original file might be corrupted. Create a new backup of the key and validate that copy.
