---
permalink: sm-settings/concept_how_do_i_interpret_iser_over_infiniband_statistics.html
sidebar: sidebar
keywords: 
summary: 'The View iSER over InfiniBand Statistics dialog box displays local target \(protocol\) statistics and iSER over InfiniBand \(IB\) interface statistics. All statistics are read-only, and cannot be set.'
---
= How do I interpret iSER over InfiniBand statistics?
:icons: font
:imagesdir: ../media/

[.lead]
The View iSER over InfiniBand Statistics dialog box displays local target (protocol) statistics and iSER over InfiniBand (IB) interface statistics. All statistics are read-only, and cannot be set.

* *Local Target (Protocol) statistics* -- Provides statistics for the iSER over InfiniBand target, which shows block-level access to its storage media.
* *iSER over InfiniBand Interface statistics* -- Provides statistics for all iSER over InfiniBand ports on the InfiniBand interface, which includes performance statistics and link error information associated with each switch port.

You can view each of these statistics as raw statistics or as baseline statistics. Raw statistics are all of the statistics that have been gathered since the controllers were started. Baseline statistics are point-in-time statistics that have been gathered since you set the baseline time.
