---
permalink: sm-settings/configure-saml-step-2.html
sidebar: sidebar
keywords: Step2, export, service, provider, files,
summary: "To establish a trust relationship between the IdP and the storage array, you import the Service Provider metadata into the IdP."
---
= Step 2: Export Service Provider files
:icons: font
:imagesdir: ../media/

[.lead]
To establish a trust relationship between the IdP and the storage array, you import the Service Provider metadata into the IdP.

.Before you begin

* You know the IP address or domain name of each controller in the storage array.

.About this task

In this task, you export metadata from the controllers (one file for each controller). The IdP needs this metadata to establish a trust relationship with the controllers and to process authorization requests. The file includes information such as the controller domain name or IP address, so that the IdP can communicate with the Service Providers.

.Steps

. Click the *Export Service Provider files* link.
+
The *Export Service Provider Files* dialog box opens.

. Enter the controller IP address or DNS name in the *Controller A* field, and then click *Export* to save the metadata file to your local system. If the storage array includes two controllers, repeat this step for the second controller in the *Controller B* field.
+
After you click *Export*, the Service Provider metadata is downloaded to your local system. Make a note of where the file is stored.

. From the local system, locate the Service Provider metadata file(s) you exported.
+
There is one XML-formatted file for each controller.

. From the IdP server, import the Service Provider metadata file(s) to establish the trust relationship. You can either import the files directly or you can manually enter the controller information from the files.
