---
permalink: sm-settings/configure-saml-step-5.html
sidebar: sidebar
keywords: Step5, enable, saml,
summary: "Your final step is to enable SAML user authentication."
---
= Step 5: Enable SAML
:icons: font
:imagesdir: ../media/

[.lead]
Your final step is to enable SAML user authentication.

.Before you begin

* The IdP metadata file is imported into System Manager.
* A Service Provider metadata file for each controller is imported into the IdP system for the trust relationship.
* At least one Monitor and one Security Admin role mapping is configured.

.About this task

This task describes how to finish the SAML configuration for user authentication. During this process, the system also prompts you to test an SSO login. The SSO Login test process is described in the previous step.

[NOTE]
====
*Editing and Disabling.* Once SAML is enabled, you _cannot_ disable it through the user interface, nor can you edit the IdP settings. If you need to disable or edit the SAML configuration, contact Technical Support for assistance.
====

.Steps

. From the *SAML* tab, select the *Enable SAML* link.
+
The *Confirm Enable SAML* dialog opens.

. Type `enable`, and then click *Enable*.
. Enter user credentials for an SSO login test.

.Results

After the system enables SAML, it terminates all active sessions and begins authenticating users through SAML.
