---
permalink: sm-settings/configure-saml.html
sidebar: sidebar
keywords: 
summary: 'To configure authentication for Access Management, you can use the Security Assertion Markup Language \(SAML\) capabilities embedded in the storage array. This configuration establishes a connection between an Identity Provider and the Storage Provider.'
---
= Configure SAML
:icons: font
:imagesdir: ../media/

[.lead]
To configure authentication for Access Management, you can use the Security Assertion Markup Language (SAML) capabilities embedded in the storage array. This configuration establishes a connection between an Identity Provider and the Storage Provider.

== About this task

An Identity Provider (IdP) is an external system used to request credentials from a user and to determine if that user is successfully authenticated. The IdP can be configured to provide multi-factor authentication and to use any user database, such as Active Directory. Your security team is responsible for maintaining the IdP. A Service Provider (SP) is a system that controls user authentication and access. When Access Management is configured with SAML, the storage array acts as the Service Provider for requesting authentication from the Identity Provider. To establish a connection between the IdP and storage array, you share metadata files between these two entities. Next, you map the IdP user entities to the storage array roles. And finally, you test the connection and SSO logins before enabling SAML.

[NOTE]
====
*SAML and Directory Services*. If you enable SAML when Directory Services is configured as the authentication method, SAML supersedes Directory Services in System Manager. If you disable SAML later, the Directory Services configuration returns to its previous configuration.
====

[NOTE]
====
*Editing and Disabling.* Once SAML is enabled, you _cannot_ disable it through the user interface, nor can you edit the IdP settings. If you need to disable or edit the SAML configuration, contact Technical Support for assistance.
====

Configuring SAML authentication is a multi-step procedure.
