---
permalink: sm-settings/enable-or-disable-resource-provisioning-for-new-volumes.html
sidebar: sidebar
keywords: SANtricity, 11.7, System Manager, E-Series, enable, disable, resource, provisioning,
summary: "If you previously disabled the default feature for resource provisioning, you can go to Settings and re-enable it for any new SSD volume groups or pools that you create. You can also disable the setting again."
---
= Enable or disable resource provisioning for new volumes
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
If you previously disabled the default feature for resource provisioning, you can go to Settings and re-enable it for any new SSD volume groups or pools that you create. You can also disable the setting again.

.Before you begin

* You must have an EF300 or EF600 storage array.
* You must have SSD volume groups or pools, where all the drives support the NVMe Deallocated or Unwritten Logical Block Error Enable (DULBE) error recovery capability.

.About this task

Resource provisioning is a feature available in the EF300 and EF600 storage arrays, which allows volumes to be put in use immediately with no background initialization process. By default, resource provisioning is enabled on systems where the drives support DULBE. You can disable that default setting from menu:Storage[Pools & Volume Groups]. If you want to re-enable resource provisioning again, you can do so by following the steps in this task. By re-enabling it, only newly created volume groups and pools are affected. Any existing volume groups and pools with resource provisioning enabled will remain unchanged.

.Steps

. Select menu:Settings[System].
. Scroll down to *Additional Settings*, and then click *Enable/Disable Resource-provisioned Volumes*.
+
The setting description indicates whether resource provisioning is currently enabled or disabled.

. In the dialog box, confirm the operation.

.Results

Enabling or disabling resource provisioning affects only new SSD pools or volume groups that you create. Existing pools or volume groups remain unchanged.
