---
permalink: sm-settings/overview-drive-security.html
sidebar: sidebar
keywords: system, security, key, management,
summary: "Security key management is available from the System page."
---
= Drive security overview
:icons: font
:imagesdir: ../media/

[.lead]
You can configure drive security and key management from the Security Key Management page.

== What is Drive Security?

Drive Security is a feature that prevents unauthorized access to data on secure-enabled drives when removed from the storage array. These drives can be either Full Disk Encryption (FDE) drives or Federal Information Processing Standard (FIPS) drives. When FDE or FIPS drives are physically removed from the array, they cannot operate until they are installed in another array, at which point, they will be in a Security Locked state until the correct security key is provided. A security key is a string of characters that is shared between these types of drives and the controllers in a storage array.

Learn more:

* link:how-the-drive-security-feature-works.html[How the Drive Security feature works]
* link:how-the-drive-security-feature-works.html[How security key management works]
* link:drive-security-terminology.html[Drive Security terminology]

== How do I configure key management?
To implement Drive Security, you must first have either FDE drives or FIPS drives installed in the array. Next, you can create either an internal key from the controller's persistent memory or an external key from a key management server. Finally, you enable Drive Security for pools and volume groups by selecting "secure-capable" in the volume settings.

Learn more:

* link:create-internal-security-key.html[Create internal security key]
* link:create-external-security-key.html[Create external security key]


== Further information
Learn more about concepts related to Drive Security:

* link:create-pool-automatically.html[Create pool automatically]
* link:create-pool-manually.html[Create pool manually]
* link:create-volume-group.html[Create volume groups]
