---
permalink: sm-settings/overview-access-management.html
sidebar: sidebar
keywords: access, management,
summary: "Access Management is a method of establishing user authentication in SANtricity System Manager. Authentication methods include RBAC (role-based access control), Directory Services, and Security Assertion Markup Language (SAML) 2.0."
---
= Access Management overview
:icons: font
:imagesdir: ../media/

[.lead]
Access Management is a method of establishing user authentication in SANtricity System Manager. Authentication methods include RBAC (role-based access control), Directory Services, and Security Assertion Markup Language (SAML) 2.0.

== What authentication methods are available?

The following authentication methods are available:

 ** *Local user roles* -- Authentication is managed through RBAC (role-based access control) capabilities enforced in the storage array. Local user roles include pre-defined user profiles and roles with specific access permissions.
 ** *Directory services* -- Authentication is managed through an LDAP (Lightweight Directory Access Protocol) server and directory service, such as Microsoft's Active Directory.
 ** *SAML* -- Authentication is managed through an Identity Provider (IdP) using the Security Assertion Markup Language (SAML) 2.0.

Learn more:

 * link:how-access-management-works.html[How Access Management works]
 * link:access-management-terminology.html[Access Management terms]
 * link:permissions-for-mapped-roles.html[Permissions for mapped roles]
 * link:access-management-with-local-user-roles.html[Local user roles]
 * link:access-management-with-directory-services.html[Directory services]
 * link:access-management-with-saml.html[SAML]

== How do I configure authentication?

The storage array is pre-configured to use local user roles, which are an implementation of RBAC (role-based access control) capabilities. If you want to configure a different method, go to the Access Management page, under Settings.

Learn more:


* link:view-local-user-roles.html[View local user roles]
* link:add-directory-server.html[Add an LDAP directory server]
* link:configure-saml.html[Configure SAML]

== Related information

Learn more about tasks related to access management:

* link:change-passwords.html[Change passwords]
* link:view-audit-log-activity.html[View audit log activity]
