---
permalink: sm-settings/generic-certificates.html
sidebar: sidebar
keywords: certificates,
summary: "You can use System Manager to create Certificate Signing Requests (CSRs), import certificates, and manage existing certificates."
---
= Certificates
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to create Certificate Signing Requests (CSRs), import certificates, and manage existing certificates.

== What are certificates?
Certificates are digital files that identify online entities, such as websites and servers, for secure communications on the internet. There are two types of certificates: a signed certificate is validated by a certificate authority (CA), which is a trusted third-party organization, and a self-signed certificate that it is validated by the owner of the entity instead of a third party.

Learn more:

* link:how-certificates-work-sam.html[How certificates work]
* link:certificate-terminology.html[Certificate terms]

== How do I configure signed certificates?
You first generate a signing request from System Manager, then send the file to a CA. Once the CA returns the certificate files, you import them using System Manager.

Learn more:

* link:use-ca-signed-certificates-for-controllers.html[Use CA-signed certificates for controllers]
* link:use-ca-signed-certificates-for-authentication-with-a-key-management-server.html[Use CA-signed certificates for authentication with a key management server]

== Related information

* link:view-imported-certificates.html[View imported certificate information]
* link:enable-certificate-revocation-checking.html[Enable certificate revocation checking]
