---
permalink: sm-settings/task_step_2_import_certificates_for_key_management_server.html
sidebar: sidebar
keywords: 
summary: 'As the next step, you import certificates for authentication between the storage array and the key management server. There are two types of certificates: the client certificate validates the storage array’s controllers, while the key management server certificate validates the server.'
---
= Step 2: Import certificates for the key management server
:icons: font
:imagesdir: ../media/

[.lead]
As the next step, you import certificates for authentication between the storage array and the key management server. There are two types of certificates: the client certificate validates the storage array's controllers, while the key management server certificate validates the server.

== Before you begin

* You must be logged in with a user profile that includes Security admin permissions. Otherwise, certificate functions do not appear.
* You have a signed client certificate file (see xref:task_step_1_complete_and_submit_csr_for_authentication_with_a_key_server.adoc[Step 1]), and you have copied that file to the host where you are accessing System Manager. A client certificate validates the storage array's controllers, so the key management server can trust their Key Management Interoperability Protocol (KMIP) requests.
* You must retrieve a certificate file from the key management server, and then copy that file to the host where you are accessing System Manager. A key management server certificate validates the key management server, so the storage array can trust its IP address. You can use a root, intermediate, or server certificate for the key management server.
+
[NOTE]
====
For more information about the server certificate, consult the documentation for your key management server.
====

== About this task

This task describes how to upload certificate files for authentication between the storage array controllers and the key management server. You must load both the client certificate file for the controllers and the server certificate file for the key management server.

== Steps

. Select *Settings* > *Certificates*.
. From the *Key Management* tab, select *Import*.
+
A dialog box opens for importing the certificate files.

. Next to *Select client certificate*, click the *Browse* button to select the client certificate file for the storage array's controllers.
+
The file name displays in the dialog box.

. Next to *Select key management server's server certificate*, click the *Browse* button to select the server certificate file for your key management server. You can choose a root, intermediate, or server certificate for the key management server.
+
The file name displays in the dialog box.

. Click *Import*.
+
The files are uploaded and validated.
