---
permalink: sm-settings/task_edit_storage_array_name.html
sidebar: sidebar
keywords: 
summary: 'You can change the storage array name that appears in the title bar of SANtricity System Manager.'
---
= Edit storage array name
:icons: font
:imagesdir: ../media/

[.lead]
You can change the storage array name that appears in the title bar of SANtricity System Manager.

== Steps

. Select *Settings* > *System*.
. Under *General*, look for the *Name:* field.
+
If a storage array name has not been defined, this field displays "Unknown."

. Click the *Edit* (pencil) icon next to the storage array name.
+
The field becomes editable.

. Enter a new name.
+
A name can contain letters, numbers, and the special characters underscore (_), dash (-), and hash sign (#). A name cannot contain spaces. A name can have a maximum length of 30 characters. The name must be unique.

. Click the *Save* (check mark) icon.
+
[NOTE]
====
If you want to close the editable field without making changes, click the *Cancel* (X) icon.
====

== Results

The new name appears in the title bar of SANtricity System Manager.
