---
permalink: sm-settings/task_change_security_key.html
sidebar: sidebar
keywords: 
summary: 'At any time, you can replace a security key with a new key. You might need to change a security key in cases where you have a potential security breach at your company and want to make sure unauthorized personnel cannot access the drives’ data.'
---
= Change security key
:icons: font
:imagesdir: ../media/

[.lead]
At any time, you can replace a security key with a new key. You might need to change a security key in cases where you have a potential security breach at your company and want to make sure unauthorized personnel cannot access the drives' data.

== Before you begin

A security key already exists.

== About this task

This task describes how to change a security key and replace it with a new one. After this process, the old key is invalidated.

== Steps

. Select *Settings* > *System*.
. Under *Security key management*, select *Change Key*.
+
The Change Security Key dialog box opens.

. Enter information in the following fields.
 ** *Define a security key identifier --* (For internal security keys only.) Accept the default value (storage array name and time stamp, which is generated by the controller firmware) or enter your own value. You can enter up to 189 alphanumeric characters without spaces, punctuation, or symbols.
+
[NOTE]
====
Additional characters are generated automatically and are appended to both ends of the string you enter. The generated characters help to ensure that the identifier is unique.
====

 ** *Define a pass phrase/Re-enter pass phrase* -- In each of these fields, enter your pass phrase. The value can have between 8 and 32 characters, and must include each of the following:
  *** An uppercase letter (one or more). Keep in mind that the pass phrase is case sensitive.
  *** A number (one or more).
  *** A non-alphanumeric character, such as !, *, @ (one or more).

+
[CAUTION]
====
*Be sure to record your entries for later use* -- If you need to move a secure-enabled drive from the storage array, you must know the identifier and pass phrase to unlock drive data.
====
. Click *Change*.
+
The new security key overwrites the previous key, which is no longer valid.
+
[NOTE]
====
The path for the downloaded file might depend on the default download location of your browser.
====

. Record your key identifier, pass phrase, and the location of the downloaded key file, and then click *Close*.

== After you finish

You should validate the security key to make sure the key file is not corrupted.
