---
permalink: sm-settings/task_delete_events_from_the_audit_log.html
sidebar: sidebar
keywords: 
summary: 'You can clear the audit log of old events, which makes searching through events more manageable. You have the option of saving old events to a CSV \(comma-separated values\) file upon deletion.'
---
= Delete events from the audit log
:icons: font
:imagesdir: ../media/

[.lead]
You can clear the audit log of old events, which makes searching through events more manageable. You have the option of saving old events to a CSV (comma-separated values) file upon deletion.

== Before you begin

* You must be logged in with a user profile that includes Security admin permissions. Otherwise, the Access Management functions do not appear.

== About this task

This task describes how to remove old events from the audit log.

== Steps

. Select *Settings* > *Access Management*.
. Select the **Audit Log**tab.
. Select *Delete*.
+
The Delete Audit Log dialog box opens.

. Select or enter the number of oldest events that you want to delete.
. If you want to export the deleted events to a CSV file (recommended), keep the checkbox selected. You will be prompted to enter a file name and location when you click *Delete* in the next step. Otherwise, if you do not want to save events to a CSV file, click the checkbox to deselect it.
. Click *Delete*.
+
A confirmation dialog box opens.

. Type `delete` in the field, and then click *Delete*.
+
The oldest events are removed from the Audit Log page.
