---
permalink: sm-settings/what-do-i-need-to-know-before-backing-up-a-security-key.html
sidebar: sidebar
keywords: 
summary: 'If your original security key becomes corrupted and you do not have a backup, you will lose access to the data on drives if they are migrated from one storage array to another.'
---
= What do I need to know before backing up a security key?
:icons: font
:imagesdir: ../media/

[.lead]
If your original security key becomes corrupted and you do not have a backup, you will lose access to the data on drives if they are migrated from one storage array to another.

Before backing up a security key, keep these guidelines in mind:

* Make sure you know the security key identifier and pass phrase of the original key file.
+
[NOTE]
====
Only internal keys use identifiers. When you created the identifier, additional characters were generated automatically and appended to both ends of the identifier string. The generated characters ensure that the identifier is unique.
====

* You create a new pass phrase for the backup. This pass phrase does not need to match the pass phrase that was used when the original key was created or last changed. The pass phrase is only applied to the backup you are creating.
+
[NOTE]
====
The pass phrase for Drive Security should not be confused with the storage array's Administrator password. The pass phrase for Drive Security protects backups of a security key. The Administrator password protects the entire storage array from unauthorized access.
====

* The backup security key file is downloaded to your management client. The path for the downloaded file might depend on the default download location of your browser. Be sure to make a record of where your security key information is stored.
