---
permalink: sm-settings/what-is-host-connectivity-reporting.html
sidebar: sidebar
keywords: 
summary: 'When host connectivity reporting is enabled, the storage array continuously monitors the connection between the controllers and the configured hosts, and then alerts you if the connection is disrupted.'
---
= What is host connectivity reporting?
:icons: font
:imagesdir: ../media/

[.lead]
When host connectivity reporting is enabled, the storage array continuously monitors the connection between the controllers and the configured hosts, and then alerts you if the connection is disrupted.

Disruptions to the connection might occur if there is a loose, damaged, or missing cable, or another problem with the host. In these situations, the system might open a Recovery Guru message:

* *Host Redundancy Lost* -- Opens if either controller cannot communicate with the host.
* *Host Type Incorrect* -- Opens if the host's type is incorrectly specified on the storage array, which could result in failover problems.

You might want to disable host connectivity reporting in situations where rebooting a controller might take longer than the connection timeout. Disabling this feature suppresses Recovery Gurus messages.

[NOTE]
====
Disabling host connectivity reporting also disables automatic load balancing, which monitors and balances controller resource use. However, if you re-enable host connectivity reporting, the automatic load balancing feature is not automatically re-enabled.
====
