---
permalink: sm-settings/what-do-i-need-to-know-before-unlocking-secure-drives.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, unlocking, secure, drives,
summary: "To unlock the data from a secure-enabled drive, you must import its security key."
---
= What do I need to know before unlocking secure drives?
:icons: font
:imagesdir: ../media/

[.lead]
To unlock the data from a secure-enabled drive, you must import its security key.

Before unlocking secure-enabled drives, keep the following guidelines in mind:

* The storage array must already have a security key. The migrated drives will be re-keyed to the target storage array.
* For the drives you are migrating, you must know the security key identifier and the pass phrase that corresponds to the security key file.
* The security key file must be available on the management client (the system with a browser used for accessing System Manager).
* If you are resetting a locked NVMe drive, you must enter the drive's security ID. To locate the security ID, you must physically remove the drive and find the PSID string (maximum of 32 characters) on the drive's label. Make sure the drive is reinstalled before you start the operation.
