---
permalink: sm-settings/which-registration-methods-are-automatically-supported-for-iscsi.html
sidebar: sidebar
keywords: 
summary: 'The iSCSI implementation supports either the Internet Storage Name Service \(iSNS\) discovery method or the use of the Send Targets command.'
---
= Which registration methods are automatically supported for iSCSI?
:icons: font
:imagesdir: ../media/

[.lead]
The iSCSI implementation supports either the Internet Storage Name Service (iSNS) discovery method or the use of the Send Targets command.

The iSNS method allows for iSNS discovery between the initiators (iSCSI hosts) and targets (the controllers). You register the target controller to provide the iSNS server with the controller's iSCSI Qualified Name (IQN) and port information.

If you do not configure iSNS, the iSCSI host can send the Send Targets command during an iSCSI discovery session. In response, the controller returns the port information (for example, the Target IQN, port IP address, listening port, and Target Port Group). This discovery method is not required if you use iSNS, because the host initiator can retrieve the target IPs from the iSNS server.
