---
permalink: sm-settings/why-does-the-cannot-access-other-controller-dialog-appear.html
sidebar: sidebar
keywords: 
summary: 'When you perform certain operations related to CA certificates \(for example, importing a certificate\), you might see a dialog box prompting you to accept a self-signed certificate for the second controller.'
---
= Why does the Cannot Access Other Controller dialog box appear?
:icons: font
:imagesdir: ../media/

[.lead]
When you perform certain operations related to CA certificates (for example, importing a certificate), you might see a dialog box prompting you to accept a self-signed certificate for the second controller.

In storage arrays with two controllers (duplex configurations), this dialog box sometimes appears if SANtricity System Manager cannot communicate with the second controller or if your browser cannot accept the certificate during a certain point in an operation.

If this dialog box opens, click *Accept Self-Signed Certificate* to proceed. If another dialog box prompts you for a password, enter your Administrator password used for accessing System Manager.

If this dialog box appears again and you cannot complete a certificate task, try one of the following procedures:

* Use a different browser type to access this controller, accept the certificate, and continue.
* Access the second controller withSystem Manager, accept the self-signed certificate, and then return to the first controller and continue.
