---
permalink: sm-support/concept_what_do_the_autosupport_features_do.html
sidebar: sidebar
keywords: 
summary: 'The AutoSupport feature is made up of three individual features that you enable separately.'
---
= What do the AutoSupport features do?
:icons: font
:imagesdir: ../media/

[.lead]
The AutoSupport feature is made up of three individual features that you enable separately.

* *Basic AutoSupport* -- Allows your storage array to automatically collect and send data to technical support.
* *AutoSupport OnDemand* -- Allows technical support to request retransmission of a previous AutoSupport dispatch when needed for troubleshooting an issue. All transmissions are initiated from the storage array, not from the AutoSupport server. The storage array checks in periodically with the AutoSupport server to determine if there are any pending retransmission requests and responds accordingly.
* *Remote Diagnostics* -- Allows technical support to request a new, up-to-date AutoSupport dispatch when needed for troubleshooting an issue. All transmissions are initiated from the storage array, not from the AutoSupport server. The storage array checks in periodically with the AutoSupport server to determine if there are any pending new requests and responds accordingly.
