---
permalink: sm-support/concept_what_do_i_need_to_know_before_upgrading_drive_firmware.html
sidebar: sidebar
keywords: 
summary: 'Before upgrading your drive firmware, be aware of these items.'
---
= What do I need to know before upgrading drive firmware?
:icons: font
:imagesdir: ../media/

[.lead]
Before upgrading your drive firmware, be aware of these items.

* As a precaution, back up your data using disk-to-disk backup, volume copy (to a volume group not affected by the planned firmware upgrade), or a remote mirror.
* You might want to upgrade only a few drives to test the behavior of the new firmware to ensure it is functioning correctly. If the new firmware is functioning correctly, upgrade the remaining drives.
* If you have any failed drives, fix them before you start the firmware upgrade.
* If the drives can do an offline upgrade, stop I/O activity to all volumes associated with the drives. When I/O activity is stopped, no configuration operations associated with those volumes can occur.
* Do not remove any drives while upgrading drive firmware.
* Do not make any configuration changes to the storage array while upgrading drive firmware.
