---
permalink: sm-support/concept_dcbx_tlv_statistics.html
sidebar: sidebar
keywords: 
summary: ''
---
= DCBX TLV statistics
:icons: font
:imagesdir: ../media/

When you select Data Center Bridging Exchange (DCBX) Type Length Value (TLV) Statistics, these statistics appear:

* *Local statistics* -- The DCBX parameters configured on the controller at the factory.
* *Operational statistics* -- The DCBX parameters that result from DCBX negotiations.
* *Remote statistics* -- The DCBX parameters from the peer device that the controller is connected to, typically a switch.

|===
| Statistic| Definition
a|
iSCSI Host Port
a|
Indicates the location of the detected host port in Controller #, Port # format.
a|
Flow Control Mode
a|
The Flow Control Mode of the entire port. Valid values are Disabled, Standard, Per Priority, or Indeterminate.
a|
Protocol
a|
The communication protocol. Valid values are FCoE, FIP, iSCSI, or UNKNOWN.
a|
Priority
a|
Integer value indicating the priority number of the communication.
a|
Priority Group
a|
Integer value representing the priority group to which the protocol has been assigned.
a|
Priority Group % Bandwidth
a|
Percentage value indicating the amount of bandwidth allocated to the priority group.
a|
DCBX PFC Status
a|
Priority-based Flow Control (PFC) status of the specific port. The value is either enabled or disabled.
|===
You can find additional DCBX TLV statistics in the state capture file.
