---
permalink: sm-support/concept_how_do_i_choose_which_type_of_upgrade_to_perform.html
sidebar: sidebar
keywords: 
summary: 'You choose the type of upgrade to perform on the drive depending on the state of the pool or volume group.'
---
= How do I choose which type of upgrade to perform?
:icons: font
:imagesdir: ../media/

[.lead]
You choose the type of upgrade to perform on the drive depending on the state of the pool or volume group.

* *Online*
+
If the pool or volume group supports redundancy and is Optimal, you can use the Online method to upgrade the drive firmware. The Online method downloads firmware _while the storage array is processing I/O_ to the associated volumes using these drives. You do not have to stop I/O to the associated volumes using these drives. These drives are upgraded one at a time to the volumes associated with the drives. If the drive is not assigned to a pool or volume group, its firmware can be updated by the Online or the Offline method. System performance may be impacted when you use the Online method to upgrade drive firmware.

* *Offline*
+
If the pool or volume group does not support redundancy (RAID 0), or is degraded, you must use the Offline method to upgrade the drive firmware. The Offline method will upgrade firmware _only while all I/O activity is stopped_ to the associated volumes using these drives. You must stop all I/O to any associated volumes using these drives. If the drive is not assigned to a pool or volume group, its firmware may be updated by the Online or the Offline method.
