---
permalink: sm-support/drive-firmware-upgrades.html
sidebar: sidebar
keywords: drive, firmware, upgrades
summary: "Drive firmware controls the low-level operating characteristics of a drive. Periodically, the drive manufacturers release updates to drive firmware to add new features, improve performance, and fix defects."
---
= Drive firmware upgrades
:icons: font
:imagesdir: ../media/

[.lead]
Drive firmware controls the low-level operating characteristics of a drive. Periodically, the drive manufacturers release updates to drive firmware to add new features, improve performance, and fix defects.

== Online and offline drive firmware upgrades

There are two types of drive firmware upgrade methods: online and offline.

== Online

During an online upgrade, drives are upgraded sequentially, one at a time. The storage array continues processing I/O while the upgrade occurs. You do not have to stop I/O. If a drive can do an online upgrade, the online method is used automatically.

Drives that can do an online upgrade include the following:

* Drives in an Optimal pool
* Drives in an Optimal redundant volume group (RAID 1, RAID 5, and RAID 6)
* Unassigned drives
* Standby hot spare drives

Doing an online drive firmware upgrade can take several hours exposing the storage array to potential volume failures. Volume failure could occur in these cases:

* In a RAID 1 or RAID 5 volume group, one drive fails while a different drive in the volume group is being upgraded.
* In a RAID 6 pool or volume group, two drives fail while a different drive in the pool or volume group is being upgraded.

== Offline (parallel)

During an offline upgrade, all drives of the same drive type are upgraded at the same time. This method requires stopping I/O activity to the volumes associated with the selected drives. Because multiple drives can be upgraded concurrently (in parallel), the overall downtime is significantly reduced. If a drive can do only an offline upgrade, the offline method is used automatically.

The following drives MUST use the offline method:

* Drives in a non-redundant volume group (RAID 0)
* Drives in a non-optimal pool or volume group
* Drives in SSD cache

== Compatibility

Each drive firmware file contains information about the drive type on which the firmware runs. You can download the specified firmware file only to a compatible drive. System Manager automatically checks compatibility during the upgrade process.
