---
permalink: sm-support/what-do-i-need-to-know-before-upgrading-the-santricity-os-software.html
sidebar: sidebar
keywords: SANtricity, System Manager, E-Series, upgrading, santricity, os, software
summary: "Before you upgrade your controller’s software and firmware, be aware of these items."
---
= What do I need to know before upgrading the SANtricity OS Software?
:icons: font
:imagesdir: ../media/

[.lead]
Before you upgrade your controller's software and firmware, be aware of these items.

* You have read the  document and the `readme.txt` file and have determined that you want to do the upgrade.
* You know whether you want to upgrade your IOM firmware.
+
Normally, you should upgrade all components at the same time. However, you might decide not to upgrade the IOM firmware if you do not want to upgrade it as part of the SANtricity OS controller software upgrade or if technical support has instructed you to downgrade your IOM firmware (you can only downgrade firmware by using the command line interface).

* You know whether you want to upgrade the controller NVSRAM file.
+
Normally, you should upgrade all components at the same time. However, you might decide not to upgrade the controller NVSRAM file if your file has either been patched or is a custom version and you do not want to overwrite it.

* You know whether you want to activate now or later.
+
Reasons for activating later might include:

 ** *Time of day* -- Activating the software and firmware can take a long time, so you might want to wait until I/O loads are lighter. The controllers fail over during activation so performance might be lower than usual until the upgrade completes.
 ** *Type of package* -- You might want to test the new software and firmware on one storage array before upgrading the files on other storage arrays.

These components are part of the SANtricity OS controller software upgrade:

* *Management software* -- System Manager is the software that manages the storage array.
* *Controller firmware* -- Controller firmware manages the I/O between hosts and volumes.
* *Controller NVSRAM* -- Controller NVSRAM is a controller file that specifies the default settings for the controllers.
* *IOM firmware* -- The I/O module (IOM) firmware manages the connection between a controller and a drive shelf. It also monitors the status of the components.
* *Supervisor software* -- Supervisor software is the virtual machine on a controller in which the software runs.

As part of the upgrade process, the host's multipath/failover driver and/or HBA driver might also need to be upgraded so the host can interact with the controllers correctly.

[NOTE]
====
To determine if this is the case, see the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].
====

If your storage array contains only one controller or you do not have a multipath driver installed, stop I/O activity to the storage array to prevent application errors. If your storage array has two controllers and you have a multipath driver installed, you do not need to stop I/O activity.

CAUTION: Do not make changes to the storage array while the upgrade occurs.
