---
permalink: sm-support/what-type-of-data-is-collected-through-autosupport.html
sidebar: sidebar
keywords: 
summary: 'The AutoSupport feature contains three standard dispatch types: event dispatches, scheduled dispatches, and on-demand and remote diagnostics dispatches.'
---
= What type of data is collected through the AutoSupport feature?
:icons: font
:imagesdir: ../media/

[.lead]
The AutoSupport feature contains three standard dispatch types: event dispatches, scheduled dispatches, and on-demand and remote diagnostics dispatches.

The AutoSupport data does not contain any user data.

* *Event dispatches*
+
When events occur on the system that warrant proactive notification to technical support, the AutoSupport feature automatically sends an event-triggered dispatch.

 ** Sent when a support event on the managed storage array occurs.
 ** Includes a comprehensive snapshot of what was going on with the storage array at the time the event occurred.

* *Scheduled dispatches*
+
The AutoSupport feature automatically sends several dispatches on a regular schedule.

 ** *Daily dispatches* -- Sent once every day during a user-configurable time interval. Includes the current system event logs and performance data.
 ** *Weekly dispatches* -- Sent once every week during a user-configurable time interval and day. Includes configuration and system state information.

* *AutoSupport OnDemand and Remote Diagnostics dispatches*
 ** *AutoSupport OnDemand* -- Allows technical support to request retransmission of a previous AutoSupport dispatch when needed for troubleshooting an issue. All transmissions are initiated from the storage array, not from the AutoSupport server. The storage array checks in periodically with the AutoSupport server to determine if there are any pending retransmission requests and responds accordingly.
 ** *Remote Diagnostics* -- Allows technical support to request a new, up-to-date AutoSupport dispatch when needed for troubleshooting an issue. All transmissions are initiated from the storage array, not from the AutoSupport server. The storage array checks in periodically with the AutoSupport server to determine if there are any pending new requests and responds accordingly.
