---
permalink: sm-support/what-does-unreadable-sectors-data-show-me.html
sidebar: sidebar
keywords: 
summary: 'You can display detailed data about unreadable sectors detected on the drives in your storage array.'
---
= What does unreadable sectors data show me?
:icons: font
:imagesdir: ../media/

[.lead]
You can display detailed data about unreadable sectors detected on the drives in your storage array.

The unreadable sectors log shows the most recent unreadable sector first. The log contains the following information about the volumes that contain the unreadable sectors. The fields are sortable.

|===
| Field| Description
a|
Affected Volume
a|
Shows the label of the volume. If a missing volume contains unreadable sectors, the World Wide Identifier appears for the missing volume.
a|
Logical Unit Number (LUN)
a|
Shows the LUN for the volume. If the volume does not have a LUN, the dialog box shows NA.
a|
Assigned To
a|
Shows the hosts or host clusters that have access to the volume. If the volume is not accessible by a host, host cluster, or even a Default Cluster, the dialog box shows NA.
|===
To see additional information about the unreadable sectors, click the plus (+) sign next to a volume.

|===
| Field| Description
a|
Date/Time
a|
Shows the date and the time that the unreadable sector was detected.
a|
Volume Logical Block Address
a|
Shows the logical block address (LBA) of the volume.
a|
Drive Location
a|
Shows the drive shelf, drawer (if your drive shelf has drawers), and the bay location.
a|
Drive Logical Block Address
a|
Shows the LBA of the drive.
a|
Failure Type
a|
Shows one of the following failure types:

* *Physical* -- A physical media error.
* *Logical* -- A read error elsewhere in the stripe causing unreadable data. For example, an unreadable sector due to media errors elsewhere in the volume.
* *Inconsistent* -- Inconsistent redundancy data.
* *Data Assurance* -- A Data Assurance error.

|===
