---
permalink: um-certificates/step-2-submit-csr-files-unified.html
sidebar: sidebar
keywords: steps 2, submit, csr, file
summary: "After you create a certificate signing request (CSR) file, send it to a Certificate Authority (CA)."
---
= Step 2: Submit CSR file
:icons: font
:imagesdir: ../media/

[.lead]
After you create a certificate signing request (CSR) file, send it to a Certificate Authority (CA).

Before you begin

* You have generated the CSR file.

.About this task

In this task, you send the generated CSR file to a CA to receive signed, management certificates for the system hosting Unified Manager and the Web Services Proxy.

E-Series systems require PEM format (Base64 ASCII encoding) for signed certificates, which includes the following file types: .pem, .crt, .cer, or .key.

.Steps

. Locate the downloaded CSR file.
+
The folder location of the download depends on your browser.

. Submit the CSR file to a CA (for example, Verisign or DigiCert), and request signed certificates in PEM format.
+
[CAUTION]
====
*After you submit a CSR file to the CA, do NOT regenerate another CSR file.* Whenever you generate a CSR, the system creates a private and public key pair. The public key is part of the CSR, while the private key is kept in the system's keystore. When you receive the signed certificates and import them, the system ensures that both the private and public keys are the original pair. If the keys do not match, the signed certificates will not work and you must request new certificates from the CA.
====

.After you finish

When the CA returns the signed certificates, go to link:step-3-import-management-certificates-unified.md#[Step 3: Import management certificates].
