---
permalink: um-certificates/what-are-the-local-users.html
sidebar: sidebar
keywords: SANtricity, Unified Manager, E-Series, local, users
summary: "Local users are predefined in the system and include specific permissions."
---
= What are the local users?
:icons: font
:imagesdir: ../media/

[.lead]
Local users are predefined in the system and include specific permissions.

Local users include:

* *admin* -- Super administrator who has access to all functions in the system. This user includes all roles. The password must be set on first-time login.
* *storage* -- The administrator responsible for all storage provisioning. This user includes the following roles: Storage Admin, Support Admin, and Monitor. This account is disabled until a password is set.
* *security* -- The user responsible for security configuration, including Access Management and Certificate Management. This user includes the following roles: Security Admin and Monitor. This account is disabled until a password is set.
* *support* -- The user responsible for hardware resources, failure data, and firmware upgrades. This user includes the following roles: Support Admin and Monitor. This account is disabled until a password is set.
* *monitor* -- A user with read-only access to the system. This user includes only the Monitor role. This account is disabled until a password is set.
* *rw* (read/write) -- This user includes the following roles: Storage Admin, Support Admin, and Monitor. This account is disabled until a password is set.
* *ro* (read only) -- This user includes only the Monitor role. This account is disabled until a password is set.
