---
permalink: um-admin/concept_administrator_password_protection_unified.html
sidebar: sidebar
keywords: 
summary: 'You must configure SANtricity Unified Manager with an administrator password to protect it from unauthorized access.'
---
= Administrator password protection
:icons: font
:imagesdir: ../media/

[.lead]
You must configure SANtricity Unified Manager with an administrator password to protect it from unauthorized access.

== Setting an administrator password

Setting an administrator password protects the software from users who unknowingly or maliciously run destructive commands. You are required to set an administrator password when you start Unified Manager for the first time.

There is one administrator password that is shared among all users. Any user who has this password can make configuration changes to storage systems.

== Entering your password

The software prompts you for the password only once during a single management session. A session times out after 30 minutes of inactivity by default, at which time, you must enter the password again. If desired, you can adjust the session timeout.

If another user accesses the software from another management client and changes the password while your session is in progress, you are prompted for a password the next time you attempt a configuration operation or a view operation.

For security reasons, you can attempt to enter a password only five times before the software enters a "lockout" state. In this state, the software rejects subsequent password attempts. You must wait 10 minutes to reset to a "normal" state before you try to enter a password again.
