---
permalink: um-admin/concept_home_page_unified.html
sidebar: sidebar
keywords: 
summary: 'Unified Manager is a web-based interface that allows you to manage multiple storage arrays in a single view.'
---
= Interface overview
:icons: font
:imagesdir: ../media/

[.lead]
Unified Manager is a web-based interface that allows you to manage multiple storage arrays in a single view.

== Main page

When you log in to Unified Manager, the main page opens to *Manage - All*. From this page, you can scroll through a list of discovered storage arrays in your network, view their status, and perform operations on a single array or on a group of arrays.

== Navigation sidebar

The navigation sidebar provides the following:

* *Manage* -- Discover storage arrays in your network, launch SANtricity System Manager for an array, import settings from one array to multiple arrays, and manage array groups. Select the check boxes next to the array names to perform operations on them, such as importing settings and creating array groups. The ellipses at the end of each row provides an in-line menu for operations on a single array, such as renaming it.
* *Operations* -- View the progress of batch operations, such as importing settings from one array to another.
+
[NOTE]
====
Some operations are not available when a storage array has a non-optimal status.
====

* *Certificate Management* -- Manage certificates to authenticate between browsers and clients.
* *Access Management* -- Establish user authentication for the Unified Manager interface.
* *Support* -- View technical support options, resources, and contacts.

== Banner functions

From the top banner, you can access Help and other documentation for the Unified Manager interface. You can also access administration options, which are available from the drop-down next to your login name.
